nasa/opera-sds-pge

.ci/docker/Dockerfile_dswx_hls, .ci/scripts/build_dswx_hls.sh, COPYING, src/opera/scripts/pge_docker_entrypoint.sh, src/opera/scripts/pge_main.py, src/opera/util/run_utils.py
This PR adds the initial set of scripts to create a combined PGE-SAS Docker Image, based on the DSWx-HLS interface image provided by ADT. This includes a Dockerfile for injecting the `opera_pge` repo into the existing DSWx-HLS image, an entrypoint script for kicking off `pge_main` when the container is invoked, and a script for building the image itself.
@JHofman728
=> DSWx-HLS PGE Dockerfile Addition

.ci/docker/Dockerfile_dswx_hls, .ci/jenkins/Jenkinsfile, .ci/scripts/build_all_images.sh, .ci/scripts/build_dswx_hls.sh, .ci/scripts/cleanup.sh, .ci/scripts/test_all_images.sh, .ci/scripts/test_dswx_hls.sh, .flake8, .gitignore, .pylintrc, requirements.txt, src/opera/scripts/pge_tests_entrypoint.sh, src/opera/test/pge/data/test_sas_error_config.yaml, src/opera/util/run_utils.py
This merge adds the initial Continuous Integration framework for the opera_pge repository. This framework was largely adapted from NISAR, and is currently intended for use with Jenkins.
A build-test-deploy Jenkins script has been added, along with all required shell scripts needed to configure a pipeline that does the following:
1. Clones the latest main branch of the opera_pge repo
2. Builds all PGE Docker images (currently this is only the DSWx-HLS image)
3. Runs flake8, pylint and pytest w/ code coverage on containers of each built Docker image
4. Uploads all Docker images to Artifactory, both as tarballs and raw Docker images.
=> CI Framework Addition

.ci/jenkins/Jenkinsfile, .ci/scripts/build_dswx_hls.sh, .ci/scripts/test_dswx_hls.sh
An update to the Jenkins CI scripts to add a stage for publishing the pytest code coverage HTML. This branch also adds some improvements to permission handling of test results to ensure that Jenkins can always cleanup successfully after a pipeline.
=> CI HTML Publishing for Code Coverage

.pylintrc, src/opera/pge/__init__.py, src/opera/pge/base_pge.py, src/opera/pge/dswx_pge.py, src/opera/pge/runconfig.py, src/opera/scripts/pge_main.py, src/opera/test/__init__.py, src/opera/test/pge/test_base_pge.py, src/opera/test/pge/test_dswx_pge.py, src/opera/test/pge/test_logger.py, src/opera/test/pge/test_pge_main.py, src/opera/test/pge/test_run_utils.py, src/opera/test/pge/test_time.py, src/opera/util/__init__.py, src/opera/util/logger.py, src/opera/util/run_utils.py, src/opera/util/time.py, src/opera/util/usage_metrics.py
These were the pylint results that I did not act upon:
from src/opera/pge:
base_pge.py:36:0: E0402: Attempted relative import beyond top-level package (relative-beyond-top-level)
base_pge.py:161:0: W0613: Unused argument 'kwargs' (unused-argument)
base_pge.py:234:0: W0613: Unused argument 'kwargs' (unused-argument)
base_pge.py:276:4: W0231: __init__ method from base class 'PreProcessorMixin' is not called (super-init-not-called)
base_pge.py:276:4: W0231: __init__ method from base class 'PostProcessorMixin' is not called (super-init-not-called)
base_pge.py:327:0: W0613: Unused argument 'kwargs' (unused-argument)
dswx_pge.py:30:0: E0402: Attempted relative import beyond top-level package (relative-beyond-top-level)
dswx_pge.py:31:0: E0402: Attempted relative import beyond top-level package …
=> Issues 20 21 22

src/opera/test/pge/test_usage_metrics.py, src/opera/util/usage_metrics.py
This PR incorporates the work contributed by @drewmee to add unit test coverage for the `usage_metrics.get_self_peak_vmm_kb()` function. Thanks again to Drew for his contributions!
Previously, testing for this function was skipped since OS file used for the check only exists on Linux based OS. The function and unit test now check to ensure the current platform is Linux or not and take the appropriate action.
Resolves #22
=> Unit test for the usage_metric.get_self_peak_vmm_kb()

.ci/jenkins/build-test-deploy/Jenkinsfile
This PR integrates a documentation creation step, via Sphinx, into the Jenkins build-test-deploy pipeline for opera-sds-pge.
The new pipeline steps do the following: 
* Create a conda environment with the requisite Python version and Sphinx dependencies installed 
* Clean any pre-existing Sphinx build directory
* Remake the HTML documentation
* Push the created HTML docs to the gh-pages branch of the opera-sds-pge repo (which triggers an automatic redeployment by GitHub)
* Clean up the installed conda environment
I also wanted an PDF generation step that uploaded the PDF manual to Artifactory, but getting a working LaTeX install on our CI machine is on-going, and will eventually be tackled in a later ticket.
=> Document Generation Step for Deployment Pipeline

src/opera/pge/templates/OPERA_ISO_metadata_L3_DSWx_HLS_template.xml.jinja2
This PR adds the initial ISO metadata template for use with the DSWx-HLS PGE.
The template is based on examples from SWOT and NISAR, and represents a "best effort" attempt at capturing the relevant metadata for the DSWx-HLS PGE for storage by the DAAC. There will likely need to be corrections and updates in the future, but I'm hoping this version captures at least 90% of the metadata worth reporting on.
@hfattahi @gshiroma Would it possible for someone from ADT to have a look over this template and determine if there's any pertinent metadata from the output GeoTIFF that should be included, but is not currently? If you search the template for `product_output` it should find all the placeholders that correspond to data that will be extracted from the DSWx-HLS metadata. Thanks!
=> ISO metadata template for DSWx-HLS PGE

src/opera/pge/base_pge.py, src/opera/pge/dswx_pge.py, src/opera/test/data/test_sas_qa_bad_extension_config.yaml, src/opera/test/pge/test_base_pge.py, src/opera/test/pge/test_dswx_pge.py, src/opera/test/util/test_render_jinja2.py, src/opera/test/util/test_run_utils.py, src/opera/util/img_utils.py, src/opera/util/render_jinja2.py, src/opera/util/usage_metrics.py
=> 77 cleanup final

src/opera/pge/dswx_pge.py, src/opera/pge/templates/OPERA_ISO_metadata_L3_DSWx_HLS_template.xml.jinja2
These changes address Issue 85 for the top-level XML entries only: https://github.com/nasa/opera-sds-pge/issues/85
The time range change mentioned in the email will be made as part of another TBD issue.
=> Issue #85 update ISO template top-level to match SWOT

requirements.txt, src/opera/test/util/test_metadata_utils.py, src/opera/util/metadata_utils.py
Initial implementation of utility to convert from MGRS tile codes to lat/lon bounding box.
=> Issue94 mgrs tile code to lat lon utility

src/opera/pge/dswx_pge.py, src/opera/pge/templates/OPERA_ISO_metadata_L3_DSWx_HLS_template.xml.jinja2, src/opera/test/util/test_metadata_utils.py, src/opera/util/img_utils.py, src/opera/util/metadata_utils.py
This PR adds the final updates to the ISO metadata for the DSWx-HLS PGE to address all feedback we received from PO.DAAC. Updates include:
- Addition of lat/lon bounding box extent to ISO metadata, leveraging the new MGRS to lat/lon utility
- Corrections to the temporal extent in the ISO metadata to specify a begin/end time range
- Replacement of the Built up cover fraction file with the Worldcover file in the ancillary input section of the ISO metadata
=> ISO metadata temporal/spatial extent updates

src/opera/pge/cslc_s1/templates/OPERA_ISO_metadata_L2_CSLC_S1_template.xml.jinja2, src/opera/pge/dswx_hls/templates/OPERA_ISO_metadata_L3_DSWx_HLS_template.xml.jinja2
This PR adds the jinja2 template for the CSLC-S1 ISO metadata. There are also some updates made to the existing DSWx-HLS template to capture some additional metadata parameters from the output product, as well as address the issues from #133
=> CSLC S1 ISO Template

src/opera/pge/base/runconfig.py, src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/dswx_hls/dswx_hls_pge.py, src/opera/test/data/test_cslc_s1_config.yaml, src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py
This branch adds an implementation for file name application to the CSLC-S1 PGE.
The information required to fill in the components of the final filename are obtained from the JSON metadata file produced by the SAS.
This branch also modifies the `get_output_product-filenames()` method of the `RunConfig` class to support finding of output products within an arbitrary number of sub-directories.
=> CSLC-S1 Filename Convention Application

.ci/scripts/build_cslc_s1.sh, src/opera/pge/cslc_s1/schema/cslc_s1_sas_schema.yaml, src/opera/test/data/test_cslc_s1_config.yaml
Small update to incorporate the latest version of the CSLC-S1 interface SAS with our PGE repo. 
Main change is the removal of the `burst_file_path` and `light_metadata_path` from the list of input files expected by the SAS runconfig schema.
=> Changes to incorporate redelivery of CSLC-S1 SAS interface

.ci/jenkins/build-int-test/Jenkinsfile, .ci/scripts/test_int_dswx_hls.sh, src/opera/pge/dswx_hls/dswx_hls_pge.py, src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py
This PR addresses the recent change to the output product filename format for DSWx-HLS products where some fields were shuffled around.
I wanted to try this branch out with the Integration Test pipeline, so I also ended up make some modifications to allow the pipeline to support multiple PGE's, in expectation of the CSLC-S1 test script. I also updated the test assets for DSWx to the versions received from ADT for the CalVal delivery.
=> DSWx-HLS Filename Convention and Int Test Updates

src/opera/test/util/test_logger.py
The solution was to replace __os.chdir(self.test_dir)__ by __os.chdir(self.starting_dir)__ on __tearDown()__ method to correctly return to starting directory, so temporary directory is cleaned up appropriately without leaving a __test_logger_xxxxxtemp__  directory within whatever working directory the test was started in.
=> Return to starting directory in tearDown(), so temporary directory is cleaned up appropriately.

src/opera/pge/dswx_hls/dswx_hls_pge.py, src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py, src/opera/util/img_utils.py
This branch fixes an issue where multiple timestamps concatenated with a plus sign assigned to the `SENSING_TIME` field of DSWx-HLS metadata were propagated to the ISO metadata, resulting in validation errors.
Logic has been added to the method that collects DSWx product metadata to detect sensing time fields containing a "+", and simply parse out the first timestamp for use as the begin/end value.
=> HLS Sensing Time parsing fix

src/opera/pge/dswx_hls/dswx_hls_pge.py, src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py, src/opera/util/error_codes.py, src/opera/util/img_utils.py, src/opera/util/metadata_utils.py
This branch adds a step to the post-processor of the DSWx-HLS PGE to perform a correction to output product metadata for DSWx products based on Landsat-9 HLS inputs. Certain HLS products have been observed to be based on Landsat-9 data (based on sensor product ID), but erroneously specify Landsat-8 as the spacecraft name. In addition, this branch also adds the "L9" shortname for use when renaming products that have been corrected to specify Landsat-9 as the originating spacecraft.
=> Landsat-9 Metadata Correction

examples/cslc_s1_sample_runconfig-v2.0.0-er.2.0.yaml, examples/dswx_hls_sample_runconfig-v1.0.0-rc.4.0.yaml, src/opera/pge/base/runconfig.py, src/opera/pge/base/schema/base_pge_schema.yaml, src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/dswx_hls/dswx_hls_pge.py, src/opera/test/data/test_cslc_s1_config.yaml, src/opera/test/data/test_dswx_hls_config.yaml, src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py, src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py
Made the changes per ticket #149.  Slight schema change to add ProductVersion and CompositeReleaseID to base_pge_schema.yaml.
Minor changes to code and unit tests. Dummy values were added to runconfig files used for testing.  
Note: Currently we are not using or testing for CompositeReleaseID.
=> 149 schema update

.ci/docker/Dockerfile_rtc_s1, .ci/scripts/build_all_images.sh, .ci/scripts/build_cslc_s1.sh, .ci/scripts/build_dswx_hls.sh, .ci/scripts/build_rtc_s1.sh, .ci/scripts/test_all_images.sh, .ci/scripts/test_cslc_s1.sh, .ci/scripts/test_dswx_hls.sh, .ci/scripts/test_rtc_s1.sh, .ci/scripts/util.sh, src/opera/pge/rtc_s1/rtc_s1_pge.py, src/opera/pge/rtc_s1/schema/rtc_s1_sas_schema.yaml, src/opera/scripts/pge_main.py, src/opera/test/data/test_rtc_s1_config.yaml, src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py, src/opera/test/util/test_logger.py
Initial addition of the stub implementation for the RTC-S1 PGE. 
Note that due to the specifics of how this PGE/SAS works, I also had to add a partial implementation of the file-naming conventions to ensure the PGE does not clobber the multiple per-burst outputs from the SAS.
I also took the liberty of refactoring some common code out of the build/test CI scripts into util.sh to keep things maintainable as we add more and more of these scrips.
=> RTC-S1 Stub Implementation

src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/dswx_hls/dswx_hls_pge.py, src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py
These code changes add checking for Landsat-7 and non-Sentinel A/B datasets as input files.  Exceptions will be raised if these types of datasets are encountered by the PGE.
Issue description:
https://github.com/nasa/opera-sds-pge/issues/157
=> 157 DSWx HLS product type validation

src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/rtc_s1/rtc_s1_pge.py, src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py, src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py, src/opera/util/input_validation.py
Took validation code from cslc_s1 CslcS1PreProcessorMixin.
Parameterized and wrote the code to /opera/util/input_validation.py; then added the call back into CslcS1PreProcessorMixin.
Added call: validate_inputs(self.runconfig, self.logger, self.name) to run_preprocessor() in RtcS1PreProcessorMixin
Updated units for cslc-s1 and rtc-s1.  Ended up with 93% coverage for validate_inputs.py
=> 183 input validation

requirements.txt, src/opera/test/util/test_metadata_utils.py, src/opera/util/metadata_utils.py
- Implements get_rtc_s1_product_metadata() to retrieve RTC-S1 HDF5 product file metadata for use in ISO files.
- #182
- 
- Added test_get_rtc_s1_product_metadata() to test_metadata_utils.py to validate h5py library usage.
=> 182 Develop utilities for NetCDF metadata extraction

src/opera/pge/base/base_pge.py, src/opera/pge/rtc_s1/rtc_s1_pge.py, src/opera/pge/rtc_s1/templates/OPERA_ISO_metadata_L2_RTC_S1_template.xml.jinja2, src/opera/test/data/test_rtc_s1_config.yaml, src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py, src/opera/test/util/test_metadata_utils.py, src/opera/util/metadata_utils.py
- This branch provides an implementation for creation of the RTC-S1 ISO metadata, using the NetCDF metadata extraction utilities combined with the Jinja2 template. This branch also updates the file name conventions application to provide all fields for RTC-S1 output products.
- Resolves #197 
- Unit tests have been added for ISO metadata creation, as well as application of the file name conventions
=> RTC-S1 ISO Metadata Creation

src/opera/pge/dswx_hls/dswx_hls_pge.py, src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py
- Changed ".tiff" to ".tif" in dswx_hls_pge.py and in test_dswx_hls_pge.py
-  minor change to test_dswx_hls_pge.py
- in the future should we consider changing methods and variables with 'geotiff' in their names to 'geotif', to reinforce the new restrictions on the naming convention?
=> 209 tiff to tif

.ci/scripts/build_rtc_s1.sh, src/opera/pge/rtc_s1/rtc_s1_pge.py
Engineering Release 5.1 for the RTC-S1 PGE. This version incorporates the v0.2.1 beta delivery of the corresponding SAS. The main change is a fix to the SAS that removes a unneeded check on EPSG codes when processing burst mosaics.
=> Release 2.0.0 ER 5.1

.ci/scripts/process_metric_data.py, .ci/scripts/run_metrics.sh, .ci/scripts/test_int_cslc_s1.sh, .ci/scripts/test_int_dswx_hls.sh, .ci/scripts/test_int_rtc_s1.sh, .ci/scripts/util.sh
- This branch refactors the test_int_rtc_s1.sh script to support separate inputs for the expected input and expected output archives. The custom temp directory root argument is also now supported by the script.
- process_metric_data.py has been updated to include a `container_name` argument within its output file name convention.
- Resolves #233 
- Updates to test_int_rtc_s1.sh have been tested both directly on the OPERA PGE CI machine, as well as within the Jenkins int test pipeline.
=> RTC-S1 Test Asset Refactor

.ci/scripts/build_rtc_s1.sh, examples/rtc_s1_sample_runconfig-v2.0.0-rc.1.0.yaml, src/opera/pge/rtc_s1/rtc_s1_pge.py, src/opera/pge/rtc_s1/schema/rtc_s1_sas_schema.yaml, src/opera/pge/rtc_s1/templates/OPERA_ISO_metadata_L2_RTC_S1_template.xml.jinja2, src/opera/test/data/test_rtc_s1_config.yaml, src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py, src/opera/test/util/test_metadata_utils.py, src/opera/util/metadata_utils.py
This branch updates the RTC-S1 PGE code to integrate with the Gamma delivery of the corresponding SAS. Major changes include adding file naming support for the new "static layers" and "browse" products, and minor updates to the ISO xml metadata.
Resolves #259 
Existing unit test suite for CSLC-S1 has been updated to test file name application to the new output products.
=> RTC-S1 Gamma Integration

.ci/scripts/dswx_compare_opera_pge.py, .ci/scripts/test_int_dswx_hls.sh
- This code change enables the integration test pipeline to use the new standalone version of the DSWx HLS compare script, dswx_compare_opera_pge.py
- #208
- .ci/scripts/test_int_dswx_hls.sh passes
=> 208 Integrate standalone DSWx HLS compare script into test pipeline

examples/disp_s1_sample_runconfig-v3.0.0-er.1.0.yaml, src/opera/pge/base/runconfig.py, src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/pge/disp_s1/schema/algor_param_disp_s1_schema.yaml, src/opera/pge/dswx_s1/dswx_s1_pge.py, src/opera/test/data/test_disp_s1_algorithm_parameters.yaml, src/opera/test/data/test_disp_s1_config.yaml, src/opera/test/pge/disp_s1/test_disp_s1_pge.py, src/opera/test/pge/dswx_s1/test_dswx_s1_pge.py, src/opera/util/input_validation.py, src/opera/util/metadata_utils.py
- Updated example/test RunConfigs for DISP-S1 to include the new AlgorithmParametersSchemaPath field within the PrimaryExecutable section. This field should be set to the path to the algorithim parameters yamale schema for DISP-S1
- The existing _validate_algorithm_parameters_config() that was written for the DSWx-S1 pre-processor should also be sufficient for DISP-S1 (or any other PGE with an algo params config going forward), so the task should be to refactor this function into a utility within input_validation.py, then update both R3 PGE's to call the function in their respective pre-processors.
- Add unit tests to the DISP-S1 suite for valid/invalid validation
- #281 
- 
- Added unit tests
=> 281 DISP-S1 algorithm parameter schema validation

src/opera/test/util/test_metadata_utils.py, src/opera/util/metadata_utils.py
- This branch addresses an issue in the`metadata_utils.get_geographic_boundaries_from_mgrs_tile` function for tiles that crossed the anti-meridian. The function has been updated with fixes that were applied to the PCM version of the function, which were originally provided by Gustavo Shiroma.
- Fixes #291 
- The following unit test has been added to validate that the anti-meridian case is now handled correctly:
```python
def test_get_geographic_boundaries_from_mgrs_tile_nominal_antimeridian(self):
"""Test MGRS tile code conversion with a tile that crosses the anti-meridian"""
lat_min, lat_max, lon_min, lon_max = get_geographic_boundaries_from_mgrs_tile('T60VXQ')
self.assertAlmostEqual(lat_min, 62.13198085489144)
self.assertAlmostEqual(lat_max, 63.16076767648831) …
```
=> HLS Bounding Box Anti-meridian fix

.ci/jenkins/build-int-test/Jenkinsfile, .ci/scripts/build_cslc_s1.sh, .ci/scripts/build_rtc_s1.sh, .ci/scripts/test_int_cslc_s1.sh, .ci/scripts/test_int_dswx_hls.sh, .ci/scripts/test_int_rtc_s1.sh, src/opera/pge/base/runconfig.py, src/opera/pge/base/schema/base_pge_schema.yaml, src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/cslc_s1/templates/OPERA_ISO_metadata_L2_CSLC_S1_template.xml.jinja2, src/opera/pge/rtc_s1/rtc_s1_pge.py, src/opera/pge/rtc_s1/schema/rtc_s1_sas_schema.yaml, src/opera/pge/rtc_s1/templates/OPERA_ISO_metadata_L2_RTC_S1_template.xml.jinja2, src/opera/test/data/invalid_runconfig.yaml, src/opera/test/data/test_cslc_s1_config.yaml, src/opera/test/data/test_rtc_s1_config.yaml, src/opera/test/data/valid_runconfig_full.yaml, src/opera/test/data/valid_runconfig_no_sas.yaml, src/opera/test/pge/base/test_runconfig.py, src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py, src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py, src/opera/test/util/test_metadata_utils.py, src/opera/util/input_validation.py, src/opera/util/metadata_utils.py
- This branch updates the code for the CSLC-S1 and RTC-S1 PGE's to accommodate the CalVal release of the corresponding SAS. Updates include application of the latest "official" file naming conventions for the static layer output product(s), as well as addressing gaps in the ISO XML metadata.
* To support the new file name convention for static layer products, a new `DataValidityStartTime` field has been added to the base PGE RunConfig schema. This field contains a datetime that is used in lieu of acquisition time in the static layer output file names.
- This branch also makes several enhancements to the integration test Jenkins pipeline:
* The combined PGE/SAS .log file is now copied as a Jenkins artifact for each integration test.
* The integration test pipeline now creates a temporary …
=> R2 SAS CalVal Release Integration

src/opera/pge/dswx_s1/templates/OPERA_ISO_metadata_L3_DSWx_S1_template.xml.jinja2
- This branch adds the initial ISO xml metadata template for use with the DSWx-S1 PGE. The template placeholders were derived based on the product metadata specified by the Product Spec for the DSWx-S1 SAS Interface delivery.
- Resolves #305 
- No changes to tests in this branch. Testing of the template will occur once mock metadata (#304) is available.
=> DSWx-S1 ISO XML Metadata Template

.ci/scripts/test_int_util.sh
- The metrics collection background process does not get cleaned up if the integration test scripts exit unexpectedly before the metrics_collection_end function has a chance to run.  This change will end the process if the cleanup trap is triggered.
- #310 
- 
- Simulated an early exit of an integration test script to test that the process gets terminated.
=> Issue 310 Add code to end metrics collection process to trap cleanup

.ci/docker/Dockerfile_rtc_s1, .ci/scripts/build_rtc_s1.sh, .ci/scripts/test_rtc_s1.sh, examples/cslc_s1_sample_runconfig-v2.0.0-rc.2.0.yaml, examples/rtc_s1_sample_runconfig-v2.0.0-rc.2.0.yaml, requirements.txt, src/opera/pge/base/runconfig.py, src/opera/pge/base/schema/base_pge_schema.yaml, src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/rtc_s1/rtc_s1_pge.py, src/opera/pge/rtc_s1/schema/rtc_s1_sas_schema.yaml, src/opera/pge/rtc_s1/templates/OPERA_ISO_metadata_L2_RTC_S1_template.xml.jinja2, src/opera/test/data/invalid_runconfig.yaml, src/opera/test/data/test_cslc_s1_config.yaml, src/opera/test/data/test_rtc_s1_config.yaml, src/opera/test/data/valid_runconfig_full.yaml, src/opera/test/data/valid_runconfig_no_sas.yaml, src/opera/test/pge/base/test_runconfig.py, src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py, src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py, src/opera/util/input_validation.py, src/opera/util/metadata_utils.py
- This branch updates the PGE code for RTC-S1 to incorporate v4.1 of the CalVal SAS delivery. High level changes include an update to the file naming conventions for standard and static layer products, updates to the ISO metadata collection to match the latest available within the output products, and fixes to the container build scripts to support Oracle Linux 8 as the base OS of the container.
- Resolves #332 
- 
- Existing RTC-S1 unit tests have been updated to accommodate changes made by this branch.
-
=> RTC-S1 CalVal v4.1 PGE Integration

.ci/scripts/disp_validate_product_opera_pge.py, .ci/scripts/test_int_disp_s1.sh, src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/test/pge/disp_s1/test_disp_s1_pge.py
- Code that was written to validate the .png product needed to be enabled and tested with an updated DISP-S1 SAS delivery.
- A change was made to the DISP-S1 validation tool to ignore selective groups during comparison, and the pge_runconfig is now being excluded from comparison during the integration test.
- #326 
- #339 
- Testing was done at the unit and integration level.
=> 326 Re-enable png output product validation for DISP-S1

.ci/docker/Dockerfile_dswx_s1, .ci/scripts/build_dswx_s1.sh
- This branch fixes a bug in the container build configuration for the DSWx-S1 PGE, where a version of the hdf5 library compatible with the installation of h5py was not getting installed due to recent changes to requirements.txt
- Fixes #343 
- The test_dswx_s1.sh script now successfully runs all DSWx-S1 unit tests within the container as expected.
=> DSWx-S1 HDF5 package installation fix

.ci/scripts/build_cslc_s1.sh, .ci/scripts/test_int_cslc_s1.sh, examples/cslc_s1_sample_runconfig-v2.0.0.yaml, requirements.txt, src/opera/pge/base/schema/base_pge_schema.yaml, src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/cslc_s1/schema/cslc_s1_sas_schema.yaml, src/opera/pge/cslc_s1/templates/OPERA_ISO_metadata_L2_CSLC_S1_template.xml.jinja2, src/opera/test/data/test_cslc_s1_config.yaml, src/opera/test/data/test_cslc_s1_static_config.yaml, src/opera/test/data/test_dswx_s1_config.yaml, src/opera/test/data/test_rtc_s1_config.yaml, src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py, src/opera/test/util/test_logger.py, src/opera/util/metadata_utils.py
- This branch integrates the Final SAS delivery for CSLC-S1 with the PGE library. Expected assets for the integration test have been updated, as well as the example RunConfig. This branch also updates the base PGE schema to allow product version to be a string or a number, so we can support specifying multi-part version numbers (i.e. 1.0.0 and not just 1.0).
- Resolves #352 
- Unit tests have been updated to account for the change to the base PGE schema.
- The CSLC SAS image now utilizes Python 3.11, which changes the default behavior for how `IntEnum` values (such as our `ErrorCode` enum) are represented as strings. An affected test in `test_logger.py` has been updated to support both Python 3.11 and previous.
=> CSLC-S1 SAS Final PGE Integration

requirements.txt, src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/test/data/test_disp_s1_config.yaml, src/opera/test/pge/disp_s1/test_disp_s1_pge.py
- Produce ISO XML metadata using jinja1 template
- added a unit test (98% code coverage)
=> #348 add disp_s1 iso-metadata

.ci/docker/Dockerfile_disp_s1, examples/disp_s1_sample_runconfig-v3.0.0-er.5.1.yaml, src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/test/pge/disp_s1/test_disp_s1_pge.py, src/opera/util/input_validation.py
- Release v3.0.0-er.5.1 for the DISP-S1 PGE. This version makes the input/ancillary product validation stage optional based on the setting of the DebugMode flag in the RunConfig. This was done for better compatibility with PCM integration, where some or all ancillary inputs will not be available for initial integration testing.
- This release also fixes an issue in the grib_to_netcdf stage where provided NetCDF files were not included in the modified runconfig provided to the SAS.
=> DISP-S1 Release v3.0.0-er.5.1

.ci/scripts/cslc_s1/build_cslc_s1.sh, .ci/scripts/cslc_s1/opera_pge_cslc_s1_delivery_6.1_final_runconfig.yaml, .ci/scripts/cslc_s1/opera_pge_cslc_s1_static_delivery_6.1_final_runconfig.yaml, .ci/scripts/cslc_s1/test_int_cslc_s1.sh, .ci/scripts/disp_s1/build_disp_s1.sh, .ci/scripts/disp_s1/opera_pge_disp_s1_r3_beta_runconfig.yaml, .ci/scripts/disp_s1/test_int_disp_s1.sh, .ci/scripts/dswx_hls/build_dswx_hls.sh, .ci/scripts/dswx_hls/compare_dswx_hls_products.sh, .ci/scripts/dswx_hls/dswx_hls_compare.py, .ci/scripts/dswx_hls/opera_pge_dswx_hls_delivery_4.1_final_runconfig.yaml, .ci/scripts/dswx_hls/test_int_dswx_hls.sh, .ci/scripts/dswx_s1/build_dswx_s1.sh, .ci/scripts/dswx_s1/dswx_s1_gamma_0.3_runconfig.yaml, .ci/scripts/dswx_s1/test_int_dswx_s1.sh, .ci/scripts/metrics/plot_metric_data.py, .ci/scripts/metrics/process_metric_data.py, .ci/scripts/rtc_s1/build_rtc_s1.sh, .ci/scripts/rtc_s1/opera_pge_rtc_s1_delivery_5_final_runconfig.yaml, .ci/scripts/rtc_s1/opera_pge_rtc_s1_static_delivery_5_final_runconfig.yaml, .ci/scripts/rtc_s1/test_int_rtc_s1.sh, .ci/scripts/util/test_int_util.sh, .ci/scripts/util/util.sh
- This branch lays the initial groundwork of refactoring the PGE integration tests such that the product comparison step is now performed within the PGE container. Currently, only DSWx-HLS is affected by this branch.
- The product comparison logic has been refactored into its own shell script, `compare_dswx_hls_products.sh`
- The new comparison script is now configured as the "Quality Assurance" step of PGE execution within the RunConfig used with the integration test
- The RunConfigs used with all integration tests are now part of the repository, rather than downloaded from S3
- The `.ci/scripts/<pge>` directory is now copied into PGE containers at build time, so the comparison scripts are available to the PGE at runtime
- Resolves #401 
- Branch was tested on opera-dev-pge by running …
=> DSWx-HLS Integration Test Comparison Step Refactor

.ci/scripts/disp_s1/test_int_disp_s1.sh, src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/test/data/test_disp_s1_config.yaml, src/opera/test/pge/disp_s1/test_disp_s1_pge.py
- This branch integrates the v4.1 delivery of the DISP-S1 SAS with the latest PGE code
- Support for application of file naming conventions for Compressed CSLC products has also been added
- Resolves #430 
- Unit tests have been updated to test application of the CCSLC file name conventions
- Integration test has been updated to use the latest expected assets delivered with v4.1
=> DISP-S1 SAS Gamma 4.1 Integration

src/opera/test/data/test_sas_error_config.yaml, src/opera/test/pge/base/test_base_pge.py, src/opera/util/run_utils.py
- This branch enhances the error reporting from SAS failures by utilizing a regular expression to capture a full traceback stack from the log, rather than just the last 20 lines.
- Resolves #423
- Unit test for a failing SAS condition has been updated to ensure the full traceback (which is longer than 20 lines in this test) is now provided in the error message that would be reported to an SDS end user.
=> Enhanced traceback capture for SAS failures

.ci/scripts/cslc_s1/compare_cslc_s1_products.sh, .ci/scripts/cslc_s1/compare_cslc_s1_static_products.sh, .ci/scripts/dswx_hls/compare_dswx_hls_products.sh, .ci/scripts/dswx_ni/compare_dswx_ni_products.sh, .ci/scripts/dswx_s1/compare_dswx_s1_products.sh, .ci/scripts/rtc_s1/compare_rtc_s1_products.sh, .ci/scripts/rtc_s1/compare_rtc_s1_static_products.sh
- <[add the validation checks in .ci.scripts))>
- Resolves #450 
- <None>
=> add the validation checks in .ci.scripts

.ci/scripts/dswx_ni/opera_pge_dswx_ni_delivery_0.1_interface_runconfig.yaml, examples/dswx_ni_sample_runconfig-v4.0.0-er.1.0.yaml, src/opera/pge/dswx_ni/dswx_ni_pge.py, src/opera/pge/dswx_ni/templates/OPERA_ISO_metadata_L3_DSWx_NI_template.xml.jinja2, src/opera/test/data/test_dswx_ni_config.yaml, src/opera/test/pge/dswx_ni/test_dswx_ni_pge.py, src/opera/util/mock_utils.py
- This branch adds support for generation of the ISO xml ancillary output product for DSWx-NI.
- The current interface delivery does not include any metadata within the output product, so metadata is currently sourced from a mock implementation using dummy values
- Resolves #447 
- Unit test suite for DSWx-NI has been updated to test creation of the ISO xml output product, as well as application of file naming conventions for said product
=> DSWx-NI ISO XML Generation

.ci/scripts/dswx_s1/build_dswx_s1.sh, .ci/scripts/dswx_s1/dswx_s1_final_1.1_runconfig.yaml, .ci/scripts/dswx_s1/test_int_dswx_s1.sh, examples/dswx_s1_sample_runconfig-v3.0.1.yaml, src/opera/pge/dswx_s1/dswx_s1_pge.py, src/opera/pge/dswx_s1/schema/dswx_s1_sas_schema.yaml, src/opera/test/data/test_dswx_s1_config.yaml
This release updates the utilized version of the DSWx-S1 SAS to the v1.1 Final delivery. This delivery resolves an issue where the wrong output MGRS tiles could be produced in certain regions of the globe (near poles or equator).
=> DSWx-S1 Release v3.0.1

.ci/jenkins/build-int-test/Jenkinsfile, .ci/jenkins/build-test-deploy/Jenkinsfile, .ci/jenkins/delete-tmp-dirs/Jenkinsfile
- To avoid complexities with keeping conda up to date on CI, reconfigure pipelines that use conda to install a copy locally, then delete it when finished.
- Each pipeline run installs to a unique directory under `/var/lib/jenkins/conda_installs/` to avoid any issues in the event of concurrent pipeline runs.
- Added to cleanup pipeline to check for and delete any conda installs that are over a day old in case of pipeline failure preventing removal.
- #497 
- Ran changed pipeline on sandbox
- Was unable to simulate concurrent pipeline runs as Jenkins wouldn't schedule it
=> Remove pipeline dependency on `/usr/local/anaconda3`

src/opera/pge/dswx_ni/dswx_ni_pge.py, src/opera/pge/dswx_s1/dswx_s1_pge.py, src/opera/test/pge/dswx_ni/test_dswx_ni_pge.py, src/opera/test/pge/dswx_s1/test_dswx_s1_pge.py
Scott's patch for DSWx-S1 ISO XML issue
=> Reworked generation of custom metadata in DSWx-S1 and DSWx-NI to utilize the granule filename instead of the core filename

src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/pge/dswx_hls/dswx_hls_pge.py, src/opera/pge/dswx_s1/dswx_s1_pge.py, src/opera/pge/rtc_s1/rtc_s1_pge.py, src/opera/util/error_codes.py
- Previously in PRs #504 and #496, spin off this work to all PGEs in its own, documented feature branch
- #512 
- No changes
=> Check that ISO XML path is provided when needed and log critical failure message if not

src/opera/pge/base/base_pge.py, src/opera/pge/base/schema/iso_metadata_measured_parameters_config_schema.yaml, src/opera/pge/dswx_s1/dswx_s1_pge.py, src/opera/pge/dswx_s1/templates/dswx_s1_measured_parameters.yaml, src/opera/util/render_jinja2.py
- Moved inline Measured Parameters Config (MPC) schema into a dedicated file `src/opera/pge/base/schema/iso_metadata_measured_parameters_config_schema.yaml`
- Added fields to MPC schema:
- `attribute_type`: The parameter's EOS AdditionalAttributeDataTypeCode ([info](https://git.earthdata.nasa.gov/projects/EMFD/repos/iso-schemas/browse/resources/Codelist/eosCodelists.xml?at=606229ea84f207f42b7b477c507eb422f8996115#23)) [REQUIRED]
- Must be one of: `geographicIdentifier`, `qualityInformation`, `instrumentInformation`, `sensorInformation`, `contentInformation`, `platformInformation`, `citation.identifier`, `descriptiveKeyword`, `processingInformation`, `processingParameter`, or `commandLineArgument`
- `display_name`: Override for parameter's display name that is normally derived from the …
=> ISO XML Measured Parameter Section Further Enhancements

.ci/scripts/util/secrets_scan.sh, .ci/scripts/util/secrets_scan_compare.sh
- This branch makes some small adjustments to the instructions provided by the CI system when the secrets detection step results in new findings within the repo. The commands to be run are now explicitly described, and a step for running the "audit' phase of updating .secrets.baseline has been added.
- There's also a fix for an unescaped character in secrets_scan.sh
- Resolves #518 
- N/A
=> .secrets.baseline update procedure improvements

.ci/scripts/disp_s1/build_disp_s1.sh, .ci/scripts/disp_s1/opera_pge_disp_s1_r5.5_calval_algorithm_parameters_forward.yaml, .ci/scripts/disp_s1/opera_pge_disp_s1_r5.5_calval_algorithm_parameters_historical.yaml, .ci/scripts/disp_s1/opera_pge_disp_s1_r5.5_calval_runconfig_forward.yaml, .ci/scripts/disp_s1/opera_pge_disp_s1_r5.5_calval_runconfig_historical.yaml, .ci/scripts/disp_s1/test_int_disp_s1.sh, examples/disp_s1_sample_runconfig-v3.0.0-rc.4.1.yaml, src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/pge/disp_s1/schema/algorithm_parameters_disp_s1_schema.yaml, src/opera/pge/disp_s1/schema/disp_s1_sas_schema.yaml, src/opera/test/data/test_disp_s1_algorithm_parameters.yaml, src/opera/test/data/test_disp_s1_config.yaml, src/opera/test/pge/disp_s1/test_disp_s1_pge.py
- This branch integrates v0.4.6 of the DISP-S1 CalVal SAS delivery with the corresponding PGE code
- Notable changes in this release include formal support for the "algorithm parameter overrides" config, as well as a temporary disabling of support for "forward" mode production
- Resolves #534 
- Unit test suite for DISP-S1 has been updated to account for changes in the v0.4.6 delivery
- The integration test for DISP-S1 has been modified to only run the historical mode test for the time being. The test has been run in Jenkins with all output products passing the comparison step.
=> DISP-S1 SAS v0.4.6 Integration

examples/disp_s1_sample_runconfig-v3.0.0-rc.4.2.yaml, src/opera/pge/disp_s1/disp_s1_pge.py
PGE Release v3.0.0-rc.4.2 for DISP-S1
=> DISP-S1 Release 3.0.0-rc.4.2

src/opera/pge/disp_s1/disp_s1_pge.py
PGE Release v3.0.0 for DISP-S1. This release incorporates v0.5.1 of the "Final" DISP-S1 SAS delivery.
=> DISP-S1 PGE Release v3.0.0

.ci/jenkins/build-test-deploy/Jenkinsfile, .ci/jenkins/build-test/Jenkinsfile, examples/dist_s1_sample_runconfig-v6.0.0-er.1.0.yaml, src/opera/_package.py, src/opera/test/data/test_dist_s1_config.yaml
- Initial Engineering Release v1.0 of the DIST-S1 PGE
- Part of #555 
- Regular testing
=> DIST-S1 ER1.0 Release

.ci/jenkins/build-int-test/Jenkinsfile, .ci/jenkins/build-test-deploy/Jenkinsfile, .ci/jenkins/delete-tmp-dirs/Jenkinsfile
- Clean up conda package cache when environments are uninstalled
- Ensure the conda environment removal post steps are always run, even if prior docker cleanup script step fails
- Stop the cleanup pipeline from failing if conda install dir doesn't exist (doesn't have much effect re disk usage but the pipeline shouldn't fail if it has nothing to clean)
- #556 
- Ran int test pipelines in sandbox
=> Update Jenkins pipelines to be more aggressive in cleaning up build temp data

src/opera/pge/base/schema/iso_metadata_measured_parameters_config_schema.yaml, src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/pge/disp_s1/templates/disp_s1_measured_parameters.yaml, src/opera/pge/rtc_s1/rtc_s1_pge.py, src/opera/test/pge/disp_s1/test_disp_s1_pge.py, src/opera/util/h5_utils.py
- Add new option `optional` to MPC to instruct PGE to log warning if a parameter is missing. Currently only applicable to DISP-S1, CLSC-S1 and RTC-S1 with MPC configured for DISP-S1 parameters that are copied from the source CSLC
- Fixes #567 
- Added unit test
=> Patch augment_measured_parameters behavior for non-TIFF PGEs

src/opera/pge/dswx_hls/dswx_hls_pge.py, src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py, src/opera/util/dataset_utils.py
- This branch adds support for utilizing HLS inputs based on Sentinel 2C (and eventually 2D) acquisitions in the DSWx-HLS PGE.
- Resolves #569 
- Unit tests for DSWx-HLS updated where necessary
- DSWx-HLS PGE integration test passes
- Ran image based on this branch using the HLS granule `HLS.S30.T42UVG.2025022T065231.v2.0`, which was shown to be based on Sentinel-2C from a job failure in PCM.
=> DSWx-HLS Sentinel 2-C/D Support

src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/pge/disp_s1/templates/OPERA_ISO_metadata_L3_DISP_S1_template.xml.jinja2, src/opera/pge/disp_s1/templates/disp_s1_measured_parameters.yaml, src/opera/pge/rtc_s1/rtc_s1_pge.py
- Escape some measured parameter values
- Fix bug with missing MPs not being skipped properly
- Also fixed in CSLC-S1; fix was already present in RTC-S1
- Removed obsolete reference to troposphere files from template
- #571 
- Ran integration test on dev-pge and inspected ISO XML file and PGE log file
=> DISP-S1 ISO XML patches

src/opera/pge/base/base_pge.py, src/opera/pge/cslc_s1/cslc_s1_pge.py, src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/pge/dswx_hls/dswx_hls_pge.py, src/opera/pge/dswx_s1/dswx_s1_pge.py, src/opera/pge/rtc_s1/rtc_s1_pge.py, src/opera/util/render_jinja2.py
- Move the base implementation of `augment_measured_parameters` and its specialized overrides in CSLC-S1, RTC-S1 and DISP-S1 into the `opera.util.render_jinja2` module
- Resolves #579 
- Verified unit tests still pass (local)
- Ran int tests on opera-dev-pge for PGEs using `augment_measured_parameters` (DSWx-HLS) and `augment_hd5_measured_parameters` (CSLC-S1) with images built off the main branch and this PR and diff'd an iso XML for a sample product from each to validate no significant changes/regressions in template filling occurred
- Some more PGE int tests to check nothing else broke (Particularly RTC-S1, DISP-S1 and DSWx-NI)
=> Refactor Measured Parameters Augmentation Functions

src/opera/pge/dist_s1/dist_s1_pge.py, src/opera/test/pge/dist_s1/test_dist_s1_pge.py
- Added methods to DIST-S1 Postprocessor to supply DIST-S1 ancillary core filename, catalog metadata JSON filename, PGE log filename and QA log filename
- Also added commented out stub implementation for the ISO XML filename - commented out since we have unresolved questions about the output product
- Resolves #580 
- Unit tests still pass 
- On fcf853c, seeing issue with catalog metadata not populated with output products - not sure if expected at the present
=> DIST-S1 Ancillary Filenames Postprocessor

.ci/scripts/disp_s1/test_int_disp_s1.sh, .ci/scripts/dswx_hls/test_int_dswx_hls.sh
- Fixes bug in int test scripts with more than one PGE invocation & comparison step. Previously, the final test outcome overwrote all previous outcomes, meaning any test failures in prior steps would be ignored if the final step was successful. 
- Fixes #587 
- Tested on dev with DSWx-HLS PGE image with which the bug was first observed
=> Fix bug in int test scripts for DSWx-HLS & DISP-S1

.ci/scripts/cslc_s1/test_int_cslc_s1.sh, .ci/scripts/dswx_ni/test_int_dswx_ni.sh, .ci/scripts/dswx_s1/test_int_dswx_s1.sh, src/opera/pge/dist_s1/dist_s1_pge.py, src/opera/pge/dist_s1/templates/OPERA_ISO_metadata_L3_DIST_S1_template.xml.jinja2
- ACTUALLY addresses #600 (My bad!)
- No metadata field yet for acquisition time so I used the regexes in the output validation to parse the filenames
- Also included are some fixes to [an issue I found](https://github.com/nasa/opera-sds-pge/issues/595#issuecomment-2698718908) in the DSWx-S1 int test script and also found in the scripts for CSLC-S1 and DSWx-NI
- Fixes #600 
- Unit tests passing both locally & on dev-pge
- Int tests for changed PGEs running on Jenkins (sandbox job 404 - passed)
=> Fix for stale references in DIST-S1 ISO XML

src/opera/pge/dist_s1/dist_s1_pge.py, src/opera/test/pge/dist_s1/test_dist_s1_pge.py
- Implements the following features for the DIST-S1 PGE
- Flatten SAS output to product output directory
- Ensure output products are checksummed and included in catalog JSON
- Extensive validations of SAS RTC input lists to avoid SAS failures:
- Verify the co- and cross-pol RTC input lists are the same length
- Verify the combined SAS RTC input lists are a subset of the PGE input list
- Verify the input RTCs have standard filenames (important for later checks)
- Verify input RTCs are not from a mixture of Sentinel-1A and Sentinel-1C
- Verify that the co- and cross-pol RTCs are in the same order (burst-ID & acquisition time)
- Verify no cross-pol RTCs are in co-pol input lists and vice-versa
- Resolves #612
- Resolves #613
- Closes #614 
- Implemented new unit tests for DIST-S1 RTC …
=> DIST-S1 Input validations and postprocessor updates

.ci/jenkins/build-int-test/Jenkinsfile, .ci/jenkins/build-test-deploy/Jenkinsfile
- In order to avoid license issues with miniconda, switch to miniforge in int and deploy pipelines 
- Closes #602
=> Switch Jenkins conda installer to miniforge

examples/disp_s1_sample_runconfig-v3.0.5.yaml, src/opera/pge/disp_s1/disp_s1_pge.py
Release of PGE v3.0.5 for SAS deliveries 0.5.6 (DISP-S1-STATIC CalVal) & 0.5.7 (DISP-S1 Final)
=> DISP-S1 PGE Release v3.0.5 (+DISP-S1-STATIC release)

.ci/scripts/cslc_s1/compare_cslc_s1_products.sh, .ci/scripts/cslc_s1/compare_cslc_s1_static_products.sh, .ci/scripts/disp_s1/compare_disp_s1_products.sh, .ci/scripts/disp_s1/compare_disp_s1_static_products.sh, .ci/scripts/dist_s1/compare_dist_s1_products.sh, .ci/scripts/dswx_hls/compare_dswx_hls_products.sh, .ci/scripts/dswx_ni/compare_dswx_ni_products.sh, .ci/scripts/dswx_s1/compare_dswx_s1_products.sh, .ci/scripts/rtc_s1/compare_rtc_s1_products.sh, .ci/scripts/rtc_s1/compare_rtc_s1_static_products.sh, .ci/scripts/tropo/compare_tropo_products.sh
-  Ensured the ordering of columns in the product comparison results HTML is consistently "Compare Result, Output file(s), Expected file(s), Comparison output"
-  Added header row to comparison HTML pages where missing
- Closes #618 
- Ran Int pipeline on all PGEs: `dswx_hls,cslc_s1,rtc_s1,dswx_s1,disp_s1,dswx_ni,dist_s1,tropo` - all had updates to the HTML. Results can be seen in int pipeline job `618_html_column_cleanup/2/artifact/test_results/`
=> 618 HTML results column cleanup

src/opera/test/data/test_sas_log_with_traceback.txt, src/opera/test/util/test_run_utils.py, src/opera/util/run_utils.py
- This branch adds a fix to ensure that when a SAS failure occurs, only the Traceback parsed from the SAS log is included in the PGE log and what is reported to an SDS operator. Previously, the entire SAS log was mistakenly included instead of only the region matched by regular expression.
- Fixes #645 
- Added a unit test for `run_utils.get_traceback_from_log()` to confirm fix.
=> SAS Log Traceback Parsing Fix

src/opera/pge/dist_s1/dist_s1_pge.py, src/opera/test/pge/dist_s1/test_dist_s1_pge.py
- Reworks the DIST-S1 input validations to permit baseline bursts from different S1 sensors per discussion with ADT.
- Closes #648 
- Reworked test case to inject S1C granule into current set instead of baseline set.
- Ensured tests are still passing on local & dev
=> Rework RTC homogeneity check to only check current burst set

examples/tropo_sample_runconfig-v3.0.0-er.2.0.yaml, src/opera/pge/tropo/tropo_pge.py, src/opera/test/pge/tropo/test_tropo_pge.py
- Set `PGE_VERSION` to `3.0.0-er.2.0` in `tropo_pge.py` 
- Bug fix in `test_tropo_pge.py` where `input_dir` required an absolute path in some cases
- #651 
- Successfully built on Jenkins int pipeline
- Successfully built on Jenkins release pipeline
=> Release/3.0.0 er.2.0 tropo

src/opera/pge/disp_s1/disp_s1_pge.py, src/opera/test/pge/disp_s1/test_disp_s1_pge.py
- This branch adds the DISP frame number to the output Compressed CSLC file name to account for cases where overlapping frames can produce their own unique variants of a CCSLC product for the same burst.
- Resolves #657
- Unit test suite for DISP-S1 has been updated to account for the change to the CCLSC filename. All tests are passing.
=> Incorporate DISP frame number as part of Compressed CSLC output filename

.ci/scripts/tropo/opera_pge_tropo_0.2_calval_runconfig.yaml, .secrets.baseline, examples/tropo_sample_runconfig-v3.0.0-er.2.0.yaml, src/opera/pge/tropo/templates/OPERA_ISO_metadata_L4_TROPO_template.xml.jinja2, src/opera/pge/tropo/templates/tropo_measured_parameters.yaml, src/opera/pge/tropo/tropo_pge.py, src/opera/test/data/test_tropo_config.yaml, src/opera/test/pge/tropo/test_tropo_pge.py, src/opera/util/h5_utils.py
- Adds support for ISO XML and Measured Parameters Config for TROPO PGE
- Ensures that framework for populating ISO XML with TROPO output product metadata works as intended.
- There are a few outstanding values that are using placeholders until we get confirmation otherwise:
- latitude / longitude spacing: Product spec says ~0.07 degree resolution which is equivalent to roughly 8000 meters
- spatial extent: Product is global on a regular 2d grid, so we're using the min/max lat/lon values to define the spatial extent
- zone identifier: No reference in product spec, but the product is global
- start_time / end_time: Single time value per product along with a temporal_resolution metadata field of "6h". Currently using time value from product for start_time and start_time + timedelta(hours=6) …
=> TROPO ISO XML Generation

.github/ISSUE_TEMPLATE/pge_release.yml
Add a note to the release issue template for whether or not a push to GHCR should be selected in the release pipeline execution.
=> Add GHCR push criteria to release issue template

src/opera/test/data/test_sas_log_with_traceback_no_message.txt, src/opera/test/util/test_run_utils.py, src/opera/util/run_utils.py
Minor patch for regex bug where SAS exceptions without associated message data were not captured.
- Closes #731 
- Unit tests passing locally
=> Update Traceback Regex

src/opera/test/util/test_geo_utils.py, src/opera/util/geo_utils.py
- This PR addresses an issue where the `util.geo_utils.translate_utm_bbox_to_lat_lon` function would return incorrect min/max lat/lon values for certain inputs. This was due to the assumption that the upper right corner == max lat/lon and lower left corner == min lat/lon, which is not always correct for some projections. This PR fixes this issue by instead evaluating all corners of the input bounding box.
- Fixes #736 
- Added new unit test case for sample product that discovered this bug
- Updated existing test case as it also used a bbox affected by this bug
- Verified tests are passing on dev-pge
=> Patch for UTM bbox to lat/lon utility function
