.ci/docker/Dockerfile_dswx_hls
.ci/jenkins/build-test-deploy/Jenkinsfile
.ci/jenkins/build-test/Jenkinsfile
src/opera/_package.py

Updates made for OPERA SDS PGE Release 1 Engineering Release 2

Release v1.0.0 ER 2.0

---

src/opera/pge/base_pge.py
src/opera/pge/runconfig.py
src/opera/test/data/test_base_pge_input_files_config.yaml
src/opera/test/pge/test_base_pge.py
src/opera/test/pge/test_pge_main.py
src/opera/util/error_codes.py

#50 Merged with main.  Added input_data checking and one test yaml config file.

60 multi in files

---

src/opera/pge/base_pge.py
src/opera/test/pge/test_base_pge.py
src/opera/util/logger.py

This PR updates the optional Quality Assurance application step of the post-processor to put its logged content within a separate file with a '.qa.log' extension.

QA Log File Creation

---

src/opera/pge/base_pge.py
src/opera/pge/runconfig.py
src/opera/pge/templates/OPERA_ISO_metadata_L3_DSWx_HLS_template.xml.jinja2
src/opera/test/data/render_jinja_test_template.html
src/opera/test/util/test_render_jinja2.py
src/opera/util/render_jinja2.py

added render_jinja2.py and unit test.

67 render jinja2

---

.ci/docker/Dockerfile_dswx_hls
.ci/jenkins/build-test-deploy/Jenkinsfile
.ci/jenkins/build-test/Jenkinsfile
.ci/scripts/build_all_images.sh
.ci/scripts/build_dswx_hls.sh
.ci/scripts/cleanup.sh
.ci/scripts/test_all_images.sh
.ci/scripts/test_dswx_hls.sh
LICENSE.txt
src/opera/__init__.py
src/opera/_package.py
src/opera/pge/__init__.py
src/opera/pge/base_pge.py
src/opera/pge/dswx_pge.py
src/opera/pge/runconfig.py
src/opera/schema/base_pge_schema.yaml
src/opera/schema/dswx_hls_sas_schema.yaml
src/opera/schema/sample_sas_schema.yaml
src/opera/scripts/pge_main.py
src/opera/util/__init__.py
src/opera/util/error_codes.py
src/opera/util/img_utils.py
src/opera/util/logger.py
src/opera/util/metfile.py
src/opera/util/render_jinja2.py
src/opera/util/run_utils.py
src/opera/util/time.py
src/opera/util/usage_metrics.py

These changes has been made as required from Consolidation of Copyright notices #91
I have cleaned up by removing the existing copyright headers from all existing code, and ensuring that the single copyright clause has been updated in the LICENCE.txt

Fix: Consolidation of Copyright notices #91

---

.ci/scripts/build_dswx_hls.sh
.ci/scripts/process_metric_data.py
.ci/scripts/run_metrics.sh
.ci/scripts/util.sh

Cleaned  up shell scripts and added a basic process_metric_data.py.

98 docker stats

---

src/opera/pge/base_pge.py
src/opera/pge/dswx_pge.py

This PR updates the file-rename-by-extension map to be a file-rename-by-pattern-map, with the map keys supporting unix-style wildcards (*) for more flexible mapping of file names to associated rename functions.

File rename map wildcard support

---

src/opera/_package.py
src/opera/pge/dswx_pge.py
src/opera/test/pge/test_dswx_pge.py
src/opera/test/util/test_img_utils.py
src/opera/util/img_utils.py
src/opera/util/metadata_utils.py

OPERA PGE R1 Release Candidate 1

Release 1.0.0-rc.1.0

---

src/opera/scripts/pge_main.py
src/opera/test/data/test_base_pge_config.yaml
src/opera/test/data/test_base_pge_input_files_config.yaml
src/opera/test/data/test_sas_error_config.yaml
src/opera/test/data/test_sas_qa_bad_extension_config.yaml
src/opera/test/data/test_sas_qa_config.yaml
src/opera/test/pge/test_pge_main.py
src/opera/test/util/test_metfile.py
src/opera/util/error_codes.py

Added dynamic imports to pge_main.py script.
Modified test_pge_main.py to test new code.
Updated python and .yaml test files to assign BASE_PGE rather than BASE_PGE_TEST for the pge_name in testing.  This assigns a pge name that is recognized by pge_main.py

110 dyn import

---

src/opera/pge/base/base_pge.py
src/opera/pge/base/runconfig.py
src/opera/pge/base/schema/base_pge_schema.yaml
src/opera/pge/dswx_hls/dswx_hls_pge.py
src/opera/pge/dswx_hls/templates/OPERA_ISO_metadata_L3_DSWx_HLS_template.xml.jinja2
src/opera/test/data/invalid_runconfig.yaml
src/opera/test/data/test_base_pge_config.yaml
src/opera/test/data/test_base_pge_input_files_config.yaml
src/opera/test/data/test_dswx_hls_config.yaml
src/opera/test/data/test_sas_error_config.yaml
src/opera/test/data/test_sas_qa_bad_extension_config.yaml
src/opera/test/data/test_sas_qa_config.yaml
src/opera/test/data/valid_runconfig_extra_fields.yaml
src/opera/test/data/valid_runconfig_full.yaml
src/opera/test/data/valid_runconfig_no_sas.yaml
src/opera/test/pge/test_base_pge.py
src/opera/test/pge/test_runconfig.py

Removed all occurrences of PRODUCT_COUNTER and product_counter from the code.
All unit tests ran with no errors.

119 product counter

---

.ci/scripts/test_int_dswx_hls.sh

First draft of an integration test script for dswx_hls for discussion.

112 Integration test script for dswx_hls

---

.ci/jenkins/build-int-test/Jenkinsfile
.ci/scripts/test_int_dswx_hls.sh

Initial implementation of PGE integration test using Jenkins pipeline.

125 PGE integration test jenkins pipeline dswx_hls

---

src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/test/data/test_cslc_s1_config.yaml
src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py

This PR adds the validation routines for input and output products of the CSLC-S1 PGE. PR is up mostly for posterity, as I will be merging shortly to prepare releases.
P.S. I tried to make sure @JimHofman was credited in the commit messages so he would show up as a contributor on this PR but it did not seem to work, sorry Jim 🙇 ! Thanks again for the hard work though.

CSLC-S1 Input/Output Product Validation

---

examples/cslc_s1_sample_runconfig-v2.0.0-er.2.0.yaml
examples/dswx_hls_sample_runconfig-v1.0.0-rc.4.0.yaml

Added some example RunConfig files that should be usable with the latest builds of the currently available PGE's. The examples include additional documentation on the intended usage for each field.

Example RunConfigs

---

.github/pull_request_template.md

Added a pull request template, which is meant to stave-off freeform PR descriptions (like this one!)
Unfortunately it seems like the template won't take affect until this branch is merged...
Let me know if anyone has any feedback on what else they would like to see included in the template.

Added initial pull request template

---

src/opera/pge/base/base_pge.py
src/opera/pge/dswx_hls/dswx_hls_pge.py
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py
src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py
src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py
src/opera/util/img_utils.py

175 flake8

---

.ci/scripts/test_int_cslc_s1.sh
.ci/scripts/test_int_dswx_hls.sh
.ci/scripts/test_int_util.sh

The changes in this pull request have moved common functionality into a new bash function library named test_int_util.sh to reduce the creation and maintenance effort of the integration test scripts.

176 Integration shell script refactoring initial implementation

---

src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py

- Changes made to rtc-s1 pge code.  Addition of output validation methods and related unit tests.
- # 191
-  3 unit tests were made on _validate_output(), one test for each possible failure.  This was required to isolate the test cases.  Successfully ran qa shell script rtc_compare_products.sh.  No problems with jenkins run.

191 rtc s1 output val

---

src/opera/pge/base/base_pge.py
src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/pge/dswx_hls/dswx_hls_pge.py
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py
src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py

- changed files for hyphen instead of underscore and changed the respective tests for it
- #192

for issue #192 added hyphen

---

examples/cslc_s1_sample_runconfig-v2.0.0-er.4.0.yaml
examples/rtc_s1_sample_runconfig-v2.0.0-er.4.0.yaml
src/opera/_package.py
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py
src/opera/test/util/test_usage_metrics.py

- Updates performed to prepare the Engineering Release 4.0 of the R2 PGEs
- N/A
- Unit tests have been modified to address a small issue in RTC output validation, and provide a workaround for a regression in test_usage_metrics.py

Release v2.0.0 ER.4.0

---

.ci/jenkins/build-int-test/Jenkinsfile
.ci/jenkins/build-test/Jenkinsfile
.ci/scripts/test_int_rtc_s1.sh
.ci/scripts/test_int_util.sh
examples/rtc_s1_sample_runconfig-v2.0.0-er.4.0.yaml

- Initial implementation of the test_int_rtc_s1.sh integration test script
- Updates to the Jenkinsfiles to avoid cleanup.sh script interference between Jenkins projects; process ID is added to the Docker tag values 
- #202
- Standalone testing
- Jenkins testing

202 RTC-S1 Integration Test Script

---

.ci/scripts/build_rtc_s1.sh
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/pge/rtc_s1/schema/rtc_s1_sas_schema.yaml
src/opera/pge/rtc_s1/templates/OPERA_ISO_metadata_L2_RTC_S1_template.xml.jinja2
src/opera/test/data/test_rtc_s1_config.yaml
src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py
src/opera/test/util/test_metadata_utils.py
src/opera/util/input_validation.py
src/opera/util/metadata_utils.py

- This branch updates the RTC-S1 PGE code and assets to support integration with the beta delivery of the corresponding SAS. Major changes include updates to the SAS schema, improvements to the ISO xml metadata, and product of ISO metadata for each individual burst product created from the input SLC archive.
- Resolves #218 
- Unit tests for the RTC-S1 PGE have been updated to accommodate the changes made to the PGE code to support the beta release.

RTC-S1 Beta Integration

---

.ci/scripts/test_int_util.sh
examples/cslc_s1_sample_runconfig-v2.0.0-er.4.0.yaml
examples/rtc_s1_sample_runconfig-v2.0.0-er.4.0.yaml
src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/pge/cslc_s1/schema/cslc_s1_sas_schema.yaml
src/opera/test/data/test_cslc_s1_config.yaml
src/opera/test/data/test_rtc_s1_config.yaml
src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py
src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py
src/opera/util/input_validation.py

- Update input validation for static ancillary file (cslc_s1, rtc_s1)
- Updated to include rtc_s1 (ticket #218 )
- All unit test passed (ran pytest)

222 input val

---

examples/cslc_s1_sample_runconfig-v2.0.0-er.5.0.yaml
examples/rtc_s1_sample_runconfig-v2.0.0-er.5.0.yaml
src/opera/_package.py

Release branch for Engineering Release 5.0 of the R2 PGEs (CSLC-S1 and RTC-S1)

Release v2.0.0 ER5.0

---

.ci/scripts/process_metric_data.py
.ci/scripts/test_int_dswx_hls.sh
.ci/scripts/test_int_util.sh
.ci/scripts/util.sh

- This branch refactors the shared command-line argument interface used by all integration test scripts to allow the expected input and output archives to be specified as separate files. An additional argument to specify a custom location for the temporary directory has also been added to facilitate running the scripts in a non-Jenkins context.
- The integration script for the DSWx-HLS PGE has also been updated to accommodate the changes to shared interface
- The separate input/output test data assets have been uploaded to S3
- Made several small changes to reduce the output clutter within a Jenkins log
- Resolves #230 
- Changes have been tested in Jenkins against the build/int test pipeline for the 219_dswx_int_test_asset_update branch

DSWx-HLS Integration Test Asset Update

---

.ci/scripts/build_dswx_hls.sh
.ci/scripts/test_int_dswx_hls.sh
examples/dswx_hls_sample_runconfig-v1.0.0-rc.7.0.yaml
src/opera/pge/dswx_hls/dswx_hls_pge.py
src/opera/pge/dswx_hls/schema/dswx_hls_sas_schema.yaml
src/opera/pge/dswx_hls/templates/OPERA_ISO_metadata_L3_DSWx_HLS_template.xml.jinja2
src/opera/test/data/test_dswx_hls_config.yaml
src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py
src/opera/util/img_utils.py
src/opera/util/input_validation.py

Release Candidate 7.0 for the DSWx-HLS PGE

Release 1.0.0 RC 7.0

---

.ci/scripts/test_int_cslc_s1.sh

- Test assets have been updated to be compatible with https://github.com/nasa/opera-sds-pge/wiki/CSLC-S1-Beta-Acceptance-Testing-Instructions
- #232 
- Build/Integration pipeline passes for cslc_s1.

232 CSLC-S1 v2.0.0-rc.5.0 Test Asset Update

---

.ci/scripts/build_dswx_hls.sh
.ci/scripts/test_int_dswx_hls.sh
src/opera/pge/dswx_hls/dswx_hls_pge.py

Release Candidate 7.1 for the DSWx-HLS PGE

Release 1.0.0 RC 7.1

---

src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py
src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py

- Added to test file to get all coverage over  90%
- Ran the test suite successfully

239 code coverage

---

src/opera/pge/base/base_pge.py
src/opera/test/pge/base/test_base_pge.py

- Fix a bug in the qa logger.  If there is an error in the QA code the log file will still exist.
- Added a new function: _initialize_qa_logger()
- 
Added a new test: test_qa_logger()
ran flake8 and pytest

fixed qa log bug

---

src/opera/pge/dswx_hls/dswx_hls_pge.py
src/opera/pge/dswx_s1/dswx_s1_pge.py
src/opera/pge/dswx_s1/schema/dswx_s1_sas_schema.yaml
src/opera/scripts/pge_main.py
src/opera/test/data/test_dswx_hls_config.yaml
src/opera/test/data/test_dswx_s1_config.yaml
src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py
src/opera/test/pge/dswx_s1/test_dswx_s1_pge.py

- Added new DSWx-S1 pge (stubbed version
- Also changed all references to DSWx within the DSWx-HLS pge to DSWX-HLS
N/A
- ran unit tests and complete pytest

248 dswx s1 stub

---

.ci/scripts/build_dswx_hls.sh
.ci/scripts/test_int_dswx_hls.sh
examples/dswx_hls_sample_runconfig-v1.0.0.yaml
examples/dswx_hls_sample_runconfig-v1.0.1.yaml
src/opera/pge/dswx_hls/dswx_hls_pge.py
src/opera/pge/dswx_hls/schema/dswx_hls_sas_schema.yaml

Release v1.0.1 of the DSWx-HLS PGE.

DSWx-HLS Release 1.0.1

---

.ci/scripts/test_int_cslc_s1.sh
.ci/scripts/test_int_rtc_s1.sh
src/opera/_package.py

Updates for Release v2.0.0-rc.1.0 of the R2 PGEs

Release 2.0.0 RC 1.0

---

examples/dswx_s1_sample_runconfig-v3.0.0-er.1.0.yaml
src/opera/pge/base/runconfig.py
src/opera/pge/base/schema/base_pge_schema.yaml
src/opera/pge/dswx_s1/dswx_s1_pge.py
src/opera/pge/dswx_s1/schema/algorithm_parameters_s1_schema.yaml
src/opera/pge/dswx_s1/schema/dswx_s1_sas_schema.yaml
src/opera/test/data/test_algorithm_parameters_s1.yaml
src/opera/test/data/test_dswx_s1_config.yaml
src/opera/test/pge/dswx_s1/test_dswx_s1_pge.py
src/opera/util/error_codes.py
src/opera/util/metadata_utils.py

- Ticket 266:  DSWx-S1 algorithm schema validation
- made new unit tests for the new code

266 dswx s1 schema val

---

src/opera/util/input_validation.py

- This branch fixes a bug where extension validation for Ionosphere TEC files was performed incorrectly. Since the extension can change based on the year of the file's creation, all extension validation has been removed for this file type.
- Fixes #273 
- 
- No changes to existing test suite. All regression tests pass with this update.

Fixed extension validation issue for Ionosphere ancillary files

---

.ci/docker/Dockerfile_cslc_s1
src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/util/test_usage_metrics.py

Updates for Release v2.0.0-rc.1.1 of the R2 PGEs.

Release 2.0.0 RC 1.1

---

.ci/docker/Dockerfile_disp_s1
.ci/scripts/build_all_images.sh
.ci/scripts/build_disp_s1.sh
.ci/scripts/test_all_images.sh
.ci/scripts/test_disp_s1.sh
examples/disp_s1_sample_runconfig-v3.0.0-er.1.0.yaml
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/pge/disp_s1/schema/algor_param_disp_s1_schema.yaml
src/opera/pge/disp_s1/schema/disp_s1_sas_schema.yaml
src/opera/scripts/pge_main.py
src/opera/test/data/test_disp_s1_config.yaml
src/opera/test/pge/disp_s1/test_disp_s1_pge.py

- This pull request implements the items in the task list for issue 268.
- #268 
- Added .ci/scripts/test_disp_s1.sh unit test

268 DISP-S1 stub implementation

---

.ci/scripts/build_cslc_s1.sh
.ci/scripts/test_int_cslc_s1.sh
src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/pge/cslc_s1/templates/OPERA_ISO_metadata_L2_CSLC_S1_template.xml.jinja2

Release Candidate v1.2 for the CSLC-S1 PGE.

Release 2.0.0 RC 1.2

---

.ci/scripts/build_cslc_s1.sh
.ci/scripts/build_rtc_s1.sh
examples/cslc_s1_sample_runconfig-v2.0.0-rc.1.3.yaml
src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/pge/cslc_s1/schema/cslc_s1_sas_schema.yaml
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/data/test_cslc_s1_config.yaml

Release Candidate v1.3 for the CSLC-S1 and RTC-S1 PGEs.

Release 2.0.0 RC 1.3

---

examples/cslc_s1_sample_runconfig-v2.0.0-rc.2.0.yaml
examples/rtc_s1_sample_runconfig-v2.0.0-rc.2.0.yaml
src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/pge/rtc_s1/rtc_s1_pge.py

Release Candidate 2.0 for the CSLC-S1 and RTC-S1 PGEs

Release 2.0.0 RC 2.0

---

src/opera/pge/base/runconfig.py
src/opera/pge/dswx_hls/dswx_hls_pge.py
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/pge/dswx_hls/test_dswx_hls_pge.py
src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py
src/opera/test/util/test_img_utils.py
src/opera/util/img_utils.py

Set up Mock GDAL requests for DSWX-S1.  This code is shared with DSWX-HLS so verify all DSWX-HLS unit tests complete successfully.
N/A
Verify all unit tests run successfully

304 dswx s1 mock gdal

---

src/opera/pge/base/runconfig.py
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/test/data/test_disp_s1_config.yaml
src/opera/test/pge/disp_s1/test_disp_s1_pge.py

- Validation of product output for the DISP-S1 PGE 
- #306 
- Added unit test to test_disp_s1.py

306 DISP-S1 output product validation

---

examples/dswx_s1_sample_runconfig-v3.0.0-er.2.0.yaml
src/opera/pge/dswx_s1/dswx_s1_pge.py
src/opera/test/data/test_dswx_s1_config.yaml
src/opera/test/pge/dswx_s1/test_dswx_s1_pge.py

- DSWx-S1 Iso Meta Data
- unit test written
- code coverage for dswx_s1_pge.py is 91%
- No covered in testing: qa and catalog_metadata

315 iso meta data

---

.ci/jenkins/delete-tmp-dirs/Jenkinsfile

Add Jenkins file to document simple pipeline to clean up temporary files
n/a
This pipeline did what it was designed to do

317 jenkins clean up

---

examples/disp_s1_sample_runconfig-v3.0.0-er.3.0.yaml
examples/dswx_s1_sample_runconfig-v3.0.0-er.3.0.yaml
src/opera/_package.py

Engineering Release 3.0 for the R3 PGEs

Release 3.0.0 ER 3.0

---

.ci/docker/Dockerfile_cslc_s1
.ci/scripts/build_cslc_s1.sh
.ci/scripts/test_cslc_s1.sh
examples/cslc_s1_sample_runconfig-v2.0.0-rc.2.0.yaml
src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/pge/cslc_s1/schema/cslc_s1_sas_schema.yaml
src/opera/pge/cslc_s1/templates/OPERA_ISO_metadata_L2_CSLC_S1_template.xml.jinja2
src/opera/test/data/test_cslc_s1_config.yaml
src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py
src/opera/util/metadata_utils.py

- This branch updates the PGE code for CSLC-S1 to incorporate v5.1 of the CalVal SAS delivery. High level changes include an update to the file naming conventions for standard and static layer products, updates to the ISO metadata collection to match the latest available within the output products, and fixes to the container build scripts to support Oracle Linux 8 as the base OS of the container.
- Resolves #333 
- Existing CSLC-S1 unit tests have been updated to accommodate changes made by this branch.

CSLC-S1 CalVal v5.1 PGE Integration

---

examples/cslc_s1_sample_runconfig-v2.0.0-rc.2.1.yaml
examples/rtc_s1_sample_runconfig-v2.0.0-rc.2.1.yaml
src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/pge/rtc_s1/rtc_s1_pge.py

Release Candidate 2.1 for the R2 PGEs

Release 2.0.0 RC 2.1

---

.ci/scripts/build_disp_s1.sh

- Incorporate the DISP-S1 v0.1.2 SAS Image
- #322 
- The SAS image output was compared with the golden output but differs. The cause of the difference is under investigation.

322 Incorporate DISP-S1 SAS v0.1.2

---

.ci/scripts/test_int_cslc_s1.sh
.ci/scripts/test_int_rtc_s1.sh
examples/cslc_s1_sample_runconfig-v2.0.0-rc.2.1.yaml
examples/rtc_s1_sample_runconfig-v2.0.0-rc.2.1.yaml

- This branch updates the integration tests for the R2 PGEs to account for the separate workflows for baseline and static layer products, introduced in the CalVal point releases. The test assets have been updated to include the latest expected inputs/outputs for both workflows, as well as separate RunConfigs to run the each of the workflows. The static layer workflow is now executed after the baseline workflow has completed, and the results from both workflows are compared with the appropriate expected results.
- Resolves #338 
- The updated integration test scripts have been tested locally on opera-dev-pge, as well as within the Jenkins CI environment.

R2 Integration Test Static Layer Workflow updates

---

src/opera/test/util/test_metadata_utils.py
src/opera/util/metadata_utils.py

- These changes add the following functions to metadata_utils.py:
create_test_disp_metadata_product()
get_disp_s1_product_metadata
- A function to test these new functions was added to test_metadata_utils.py:
test_get_disp_s1_product_metadata()
- #327 
- Unit testing passes: .ci/scripts/test_disp_s1.sh

327 DISP-S1 Metadata Extraction Function

---

src/opera/test/data/test_disp_s1_config.yaml
src/opera/test/pge/disp_s1/test_disp_s1_pge.py
src/opera/util/input_validation.py

- # 309 Burst ID validation for DISP-S1 inputs
- N/A
- unit tests cover 100% of the new code

# 309 Burst ID validation for DISP-S1 inputs

---

src/opera/pge/disp_s1/templates/OPERA_ISO_metadata_L3_DISP_S1_template.xml.jinja2

- This branch adds the initial jinja2 template for the DISP-S1 ISO XML metadata.
- Resolves #329 
- No executable code added in this branch, so no affect to existing tests

DISP-S1 ISO XML Template Addition

---

.ci/scripts/build_rtc_s1.sh
.ci/scripts/test_int_rtc_s1.sh
examples/rtc_s1_sample_runconfig-v2.0.0.yaml
src/opera/pge/base/runconfig.py
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/pge/rtc_s1/schema/rtc_s1_sas_schema.yaml
src/opera/pge/rtc_s1/templates/OPERA_ISO_metadata_L2_RTC_S1_template.xml.jinja2
src/opera/test/data/test_rtc_s1_static_config.yaml
src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py
src/opera/test/util/test_metadata_utils.py
src/opera/util/img_utils.py
src/opera/util/input_validation.py
src/opera/util/metadata_utils.py

- This branch integrates the Final SAS delivery for RTC-S1 with the PGE library. Expected assets for the integration test have been updated, as well as the example RunConfig. This branch also adds updates to support usage of the product bounding box in the ISO XML metadata for static layer products, and adds an additional post-processing step to ensure that the static layer data access URL is injected properly into the output metadata products for the baseline RTC-S1 workflow.
- Resolves #362 
- Resolves #364 
- Resolves #365 
- Unit tests have been updated to add tests specific to the static layer workflow. Tests have also been added for the URL injection step.

RTC-S1 SAS Final PGE Integration

---

.ci/scripts/build_cslc_s1.sh
src/opera/pge/cslc_s1/cslc_s1_pge.py

Release 2.0.0

---

examples/disp_s1_sample_runconfig-v3.0.0-er.4.0.yaml
examples/dswx_s1_sample_runconfig-v3.0.0-er.4.0.yaml
src/opera/_package.py
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/pge/dswx_s1/dswx_s1_pge.py

OPERA PGE Release v3.0.0-ER.4.0

Release v3.0.0 ER.4.0

---

.ci/scripts/build_rtc_s1.sh
.ci/scripts/test_int_rtc_s1.sh
examples/rtc_s1_sample_runconfig-v2.0.1.yaml
src/opera/pge/rtc_s1/rtc_s1_pge.py

Release v2.0.1 for the RTC-S1 PGE

Release 2.0.1

---

.flake8
.pylintrc
src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/pge/base/test_runconfig.py
src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py
src/opera/test/pge/disp_s1/test_disp_s1_pge.py
src/opera/test/pge/dswx_s1/test_dswx_s1_pge.py
src/opera/test/pge/rtc_s1/test_rtc_s1_pge.py
src/opera/test/util/test_img_utils.py
src/opera/test/util/test_logger.py
src/opera/test/util/test_metadata_utils.py
src/opera/test/util/test_render_jinja2.py
src/opera/test/util/test_time.py
src/opera/test/util/test_usage_metrics.py
src/opera/util/img_utils.py
src/opera/util/input_validation.py
src/opera/util/metadata_utils.py
src/opera/util/time.py
src/opera/util/usage_metrics.py

- Cleaned things up a bit.  All the flake8 commands are clean, and I adding a few pylint commands to clean things up too.
- We are at 95% total coverage with only img_utils.py  just below 90% at 89%, I left that alone (other than generaral cleanup) since it's about to be factored into another module.  Make 'plyint' changes for  in .pylintrc and in metadata_utils.py and input_validation.py.
- All unit tests run successfully

#328 - flake8/pylint for review

---

.ci/jenkins/build-int-test/Jenkinsfile
.ci/scripts/build_cslc_s1.sh
examples/cslc_s1_sample_runconfig-v2.1.0.yaml
examples/rtc_s1_sample_runconfig-v2.1.0.yaml
src/opera/pge/cslc_s1/cslc_s1_pge.py
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/pge/cslc_s1/test_cslc_s1_pge.py

Release v2.1.0

---

.ci/scripts/diff_dswx_files.py
.ci/scripts/dswx_comparison.py
.ci/scripts/test_int_dswx_s1.sh

- <Provide a description of the changes/updates/fixes provided by the branch>
- <#359 - DSWx-S1-Beta SAS Acceptance Test>
- <#311 - Integrate comparison script usage for DSWx-S1 Integration Test>
- <Remove the background metrics collection>
- <Once the PR is created, don't forget to check the Build/Test Jenkins pipeline for your branch to ensure all tests are passing before merge>

359 dswx s1 comparison script

---

.ci/jenkins/build-int-test/Jenkinsfile
requirements.txt

- This branch fixes the setup of the local conda environment used with integration tests in Jenkins to resolve an incompatibility issue stemming from the incorrect version of numpy being installed.
- Fixes #383 
- All integration test pipelines have been run in the Jenkins sandbox, and in each case the metrics plot generation (where the incompatibility issue would first be reported by pandas) completed without issue.

Fix for CI environment numpy/panads incompatiblity

---

.ci/docker/Dockerfile_disp_s1
.ci/scripts/build_disp_s1.sh
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/test/data/test_disp_s1_config.yaml
src/opera/test/pge/base/test_base_pge.py
src/opera/test/pge/disp_s1/test_disp_s1_pge.py
src/opera/test/pge/dswx_s1/test_dswx_s1_pge.py
src/opera/test/util/test_time.py
src/opera/test/util/test_usage_metrics.py
src/opera/util/input_validation.py

- Added translation from .grb (grib) files to .nc (netcdf) to disp_s1_pge
- None
- Added unit test to test temporary sas config file created during run time.
- flake8, pytest

381 grib to netcdf

---

.ci/scripts/dswx_comparison.py
.ci/scripts/test_int_dswx_s1.sh

- Modified test script .ci/script/test_int_dswx_s1.sh by adding dswx_comparison.py into indicated line
- #311
- ran test test_int_dswx_s1.sh with output to /data/rjb/tmp/tmp.XCeU5RLzCM

comparison test for ouput and comparison files

---

examples/dswx_s1_sample_runconfig-v3.0.0-rc.1.0.yaml
src/opera/_package.py

Release Candidate 1 for the DSWx-S1 PGE

DSWx-S1 Release v3.0.0-rc.1.0

---

.ci/scripts/cslc_s1/build_cslc_s1.sh
.ci/scripts/cslc_s1/test_int_cslc_s1.sh
.ci/scripts/dswx_hls/build_dswx_hls.sh
.ci/scripts/dswx_s1/build_dswx_s1.sh
.ci/scripts/util/test_int_util.sh
.ci/scripts/util/util.sh

- Added --no-metrics and --no-cleanup switches to "test_int_<pge>.sh" shell scripts
- N/A
- Tried out new switches and verified metrics were not generated and test files were not deleted

385 shell script options

---

examples/disp_s1_sample_runconfig-v3.0.0-rc.2.0.yaml
examples/dswx_s1_sample_runconfig-v3.0.0-rc.2.0.yaml
src/opera/pge/dswx_s1/dswx_s1_pge.py

Release 3.0.0-rc.2.0 for the R3 PGEs (DSWx-S1 and DISP-S1)

Release 3.0.0-rc.2.0

---

.ci/scripts/disp_s1/build_disp_s1.sh
.ci/scripts/dswx_s1/build_dswx_s1.sh
.ci/scripts/dswx_s1/dswx_s1_calval_0.4.2_runconfig.yaml
.ci/scripts/dswx_s1/test_int_dswx_s1.sh
examples/disp_s1_sample_runconfig-v3.0.0-rc.2.1.yaml
examples/dswx_s1_sample_runconfig-v3.0.0-rc.2.1.yaml
src/opera/_package.py
src/opera/pge/base/runconfig.py
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/pge/disp_s1/templates/OPERA_ISO_metadata_L3_DISP_S1_template.xml.jinja2
src/opera/pge/dswx_s1/dswx_s1_pge.py
src/opera/pge/dswx_s1/schema/dswx_s1_sas_schema.yaml
src/opera/test/data/invalid_runconfig.yaml
src/opera/test/data/test_dswx_s1_config.yaml
src/opera/test/data/valid_runconfig_extra_fields.yaml
src/opera/test/data/valid_runconfig_full.yaml
src/opera/test/data/valid_runconfig_no_sas.yaml
src/opera/test/pge/base/test_runconfig.py
src/opera/test/pge/disp_s1/test_disp_s1_pge.py
src/opera/test/pge/dswx_s1/test_dswx_s1_pge.py

- This branch performs the necessary updates for Release Candidate 2.1 for the R3 PGEs (DSWx-S1, DISP-S1)
- This branch also addresses several bugs uncovered in PCM integration testing related to creation of the Catalog Metadata and ISO XML file when the input RunConfig has empty fields for ancillary inputs.
- This branch also corrects the file naming convention for DISP-S1 browse products to include the "_BROWSE" suffix in the filename
- N/A
- Unit test suites have been updated where necessary to test the bug fixes applied in this branch

Release 3.0.0-RC.2.1

---

.ci/jenkins/build-int-test/Jenkinsfile
.ci/jenkins/build-test-deploy/Jenkinsfile
.ci/jenkins/build-test/Jenkinsfile
examples/dswx_ni_sample_runconfig-v4.0.0-er.1.0.yaml
src/opera/pge/dswx_ni/dswx_ni_pge.py
src/opera/pge/dswx_ni/schema/dswx_ni_sas_schema.yaml

Engineering Release 1.0 for OPERA R4, comprised of the DSWx-NI PGE.
This release wraps the initial delivery of the DSWx-NI "Interface" SAS.

Release 4.0.0-ER.1.0

---

src/opera/pge/dswx_ni/dswx_ni_pge.py
src/opera/test/data/test_dswx_ni_config.yaml
src/opera/test/pge/dswx_ni/test_dswx_ni_pge.py

- Modify the dswx-ni pge so that the DSWx-NI post-processor mixin class inherit its 
output product validation function from the DSWx-S1 version.  Also write a unit test for input validation.
-  N/A
- modify and write unit tests to fully test the changes

DSWx-NI Output Product Validation #437 

---

src/opera/pge/dswx_ni/dswx_ni_pge.py
src/opera/test/data/test_dswx_ni_config.yaml
src/opera/test/pge/dswx_ni/test_dswx_ni_pge.py

- Added file name validation based on a regular expression
N/A
Added a unit test

439 dswx ni filename validation

---

.ci/scripts/dswx_ni/opera_pge_dswx_ni_delivery_0.1_interface_runconfig.yaml
examples/dswx_ni_sample_runconfig-v4.0.0-er.2.0.yaml
requirements.txt
src/opera/_package.py
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/pge/dswx_ni/dswx_ni_pge.py
src/opera/pge/dswx_s1/dswx_s1_pge.py

Engineering Release v2.0 for the R4 DSWx-NI PGE

Release 4.0.0 ER-2.0

---

docs/opera.pge.disp_s1.rst
docs/opera.pge.dswx_ni.rst
docs/opera.pge.dswx_s1.rst
docs/opera.pge.rst
docs/opera.pge.rtc_s1.rst

- Added & updated docs `.rst` files to build all PGE docs for GH Pages.
- #460 
- No testing changes.
- Tested build and deploy with sandbox pipeline. [Confirmed built docs are present](https://nasa.github.io/opera-sds-pge/opera.html).

Add new PGEs to Sphinx docs

---

src/opera/pge/dswx_ni/dswx_ni_pge.py
src/opera/pge/dswx_s1/dswx_s1_pge.py
src/opera/pge/rtc_s1/rtc_s1_pge.py
src/opera/test/data/test_dswx_s1_config.yaml
src/opera/test/pge/dswx_ni/test_dswx_ni_pge.py
src/opera/test/pge/dswx_s1/test_dswx_s1_pge.py

- Added def _'_validate_output_product_filenames(self):'_  to _dswx_s1_pge.py_
N/A
- Added unit test for the method
- flake8 for code continuity

456 DSWx_s1: Validate output product filenames

---

.ci/jenkins/delete-tmp-dirs/Jenkinsfile

- Add `docker system prune -f` to cleanup pipeline
- #464 
- Tested on sandbox
- No other testing/code changes

Add `docker system prune -f` to cleanup pipeline

---

.ci/docker/Dockerfile_dswx_s1
.ci/jenkins/build-int-test/Jenkinsfile
requirements.txt

- This PR demonstrates the patching of some vulnerabilities in the DSWx_S1 PGE image as detected by Grype. It demonstrates it is possible, though a bit tedious to work out compatibility issues. To facilitate faster checking, I added the Grype scan to the integration pipeline as well, at least temporarily.
- #472 
- Tested on the integration pipeline in the sandbox. As of commit 0c91933, all tests and qa evaluations seem to be passing and the selected vulnerabilities are removed from the report.

Demonstrate patching of vulnerabilities detected by Grype

---

src/opera/pge/dswx_s1/dswx_s1_pge.py

- Fix for potential bug identified in metadata collection. For some reason wasn't manifesting until the dictionary structure was tweaked in the work for #484 
- N/A
- N/A

Patch for potential bug in metadata collection

---

.ci/scripts/dswx_ni/build_dswx_ni.sh
.ci/scripts/dswx_ni/opera_pge_dswx_ni_delivery_0.2_beta_runconfig.yaml
.ci/scripts/dswx_ni/test_int_dswx_ni.sh
examples/dswx_ni_sample_runconfig-v4.0.0-er.2.0.yaml
src/opera/pge/dswx_ni/dswx_ni_pge.py
src/opera/pge/dswx_ni/schema/algorithm_parameters_ni_schema.yaml
src/opera/pge/dswx_ni/schema/dswx_ni_sas_schema.yaml
src/opera/pge/dswx_ni/templates/OPERA_ISO_metadata_L3_DSWx_NI_template.xml.jinja2
src/opera/test/data/test_dswx_ni_algorithm_parameters.yaml
src/opera/test/data/test_dswx_ni_config.yaml
src/opera/test/data/test_dswx_s1_algorithm_parameters.yaml
src/opera/test/pge/dswx_ni/test_dswx_ni_pge.py

- Integrate new Beta 0.2 version of DSWx-NI to PGE
- #480 
- Updated testing data to match updated config schemas
- Ran INT tests on PGE
- Build-test pipeline had no failures

DSWx-NI Beta 0.2 PGE integration

---

.ci/scripts/dswx_ni/opera_pge_dswx_ni_delivery_0.2_beta_runconfig.yaml
examples/dswx_ni_sample_runconfig-v4.0.0-er.3.0.yaml
src/opera/_package.py

- Engineering release v3.0 for DSWx-NI Beta PGE

Release 4.0.0 ER-3.0

---

examples/disp_s1_sample_runconfig-v3.0.0-rc.3.0.yaml
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/util/input_validation.py

Release Candidate v3.0 for the DISP-S1 PGE. This version incorporates the SAS CalVal delivery v0.4.2.

Release v3.0.0 RC.3.0

---

examples/dswx_s1_sample_runconfig-v3.0.2.yaml
src/opera/pge/dswx_s1/dswx_s1_pge.py

Fix for issue with ISO XML generation. See #501

DSWx-S1 Release v3.0.2

---

examples/disp_s1_sample_runconfig-v3.0.0-rc.4.0.yaml
src/opera/pge/disp_s1/disp_s1_pge.py

Integration of new SAS version 0.4.3

DISP-S1 Release v3.0.0-rc.4.0

---

.github/ISSUE_TEMPLATE/acceptance_test.yml
.github/ISSUE_TEMPLATE/pge_release.yml
.github/ISSUE_TEMPLATE/pge_sas_integration.yml

- This branch adds additional issue template types for the following common activites:
- SAS Delivery Acceptance Testing
- PGE/SAS Integration
- PGE Release
Unfortunately I don't think we can preview what these will look like rendered until this branch is merged, so for this review try to focus on information content and once its merged we can make further refinements if some of the formatting is off.
- Resolves #519 
- N/A

Github issue templates for acceptance testing, SAS integration and PGE release tasks

---

examples/disp_s1_sample_runconfig-v3.0.0-rc.4.1.yaml

PGE Release v3.0.0-rc.4.1 for DISP-S1

DISP-S1 Release v3.0.0-rc.4.1

---

.ci/scripts/disp_s1/build_disp_s1.sh
.ci/scripts/disp_s1/opera_pge_disp_s1_r6.2_final_algorithm_parameters_historical.yaml
.ci/scripts/disp_s1/opera_pge_disp_s1_r6.2_final_runconfig_historical.yaml
.ci/scripts/disp_s1/test_int_disp_s1.sh
src/opera/pge/disp_s1/disp_s1_pge.py

- Integration for latest delivery of DISP-S1 final SAS v 0.5.2
- Closes #551 
- Unit tests are passing (local)
- Int tests are currently FAILING while awaiting new golden dataset
- Other aspects of int test (ie, output files, ISO XML gen) look good

Integrate DISP-S1 final SAS delivery 0.5.2

---

examples/disp_s1_sample_runconfig-v3.0.1.yaml
src/opera/pge/disp_s1/disp_s1_pge.py

- Release for DISP-S1 PGE version 3.0.1 for SAS Final delivery version 0.5.2
- #553

DISP-S1 Release v3.0.1

---

src/opera/pge/dist_s1/dist_s1_pge.py
src/opera/test/data/test_dist_s1_config.yaml
src/opera/test/pge/dist_s1/test_dist_s1_pge.py

- File validations for PGE inputs and outputs
- #559 
- Added unit tests for all checks in validations

DIST-S1 Input/Output Validations

---

examples/disp_s1_sample_runconfig-v3.0.2.yaml
src/opera/pge/disp_s1/disp_s1_pge.py

- Release for DISP-S1 PGE version 3.0.2 for SAS Final delivery version 0.5.3
- #564

DISP-S1 Release v3.0.2

---

examples/dswx_hls_sample_runconfig-v1.0.3.yaml
src/opera/pge/dswx_hls/dswx_hls_pge.py

Release v1.0.3 of the DSWx-HLS PGE

DSWx-HLS Release v1.0.3

---

.ci/scripts/disp_s1/build_disp_s1.sh
.ci/scripts/disp_s1/opera_pge_disp_s1_r6.4_final_algorithm_parameters_historical.yaml
.ci/scripts/disp_s1/opera_pge_disp_s1_r6.4_final_runconfig_historical.yaml
.ci/scripts/disp_s1/test_int_disp_s1.sh
examples/disp_s1_sample_runconfig-v3.0.2.yaml
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/pge/disp_s1/templates/disp_s1_measured_parameters.yaml
src/opera/test/pge/disp_s1/test_disp_s1_pge.py
src/opera/util/h5_utils.py

- This branch integrates the DISP-S1 SAS v0.5.4. Notable changes include updates to the measured parameters config to include new metadata fields, as well as updates to the descriptions for existing fields based on the latest DISP-S1 product spec (v1.0).
- Resolves #594 
- Both the unit test suite and integration test for DISP-S1 have been run to ensure all tests are still passing.

DISP-S1 SAS v0.5.4 Integration

---

examples/disp_s1_sample_runconfig-v3.0.3.yaml
src/opera/pge/disp_s1/disp_s1_pge.py

Release v3.0.2 of the DISP-S1 PGE

DISP-S1 PGE Release v3.0.2

---

examples/dist_s1_sample_runconfig-v6.0.0-er.2.0.yaml
src/opera/_package.py

- Release of DIST-S1 PGE v6.0.0-er.2.0
- Integrates Beta v0.0.6 of the DIST-S1 SAS
- #605

DIST-S1 PGE Release v6.0.0-er.2.0

---

examples/disp_s1_sample_runconfig-v3.0.4.yaml
src/opera/pge/disp_s1/disp_s1_pge.py

Release v3.0.4 of the DISP-S1 PGE

DISP-S1 PGE Release v3.0.4

---

.ci/scripts/disp_s1/disp_s1_compare.py
.ci/scripts/dist_s1/dist_s1_compare.py
.pylintrc
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/pge/dist_s1/dist_s1_pge.py
src/opera/pge/tropo/tropo_pge.py
src/opera/util/geo_utils.py
src/opera/util/h5_utils.py
src/opera/util/input_validation.py
src/opera/util/logger.py
src/opera/util/mock_utils.py
src/opera/util/render_jinja2.py
src/opera/util/tiff_utils.py

- Went over the flake8 & pylint findings and tried to address as many as I could
- Closes #633 
- Verified unit tests still passing on local and dev
- Ran jenkins int tests for a set PGEs that should cover what was changed (in progress)
Currently a draft PR to trigger Jenkins to review analysis artifacts

Clean up codebase based on flake8 & pylint findings

---

src/opera/pge/tropo/tropo_pge.py
src/opera/test/data/test_tropo_config.yaml
src/opera/test/pge/tropo/test_tropo_pge.py

- Adds input/output product validation logic to `tropo_pge.py`
- Updates testing suite in `test_tropo_pge.py` to test against invalid input and output products along with the required updates to `test_tropo_config.yaml`
- Closes #641 
- Tests ran successfully on opera-dev-pge

TROPO Input/Output Product Validation

---

examples/dswx_ni_sample_runconfig-v4.0.0-er.4.0.yaml
src/opera/pge/dswx_ni/dswx_ni_pge.py

Release v4.0.0-er.4.0 of the DSWx-NI PGE

DSWx-NI PGE release v4.0.0-er.4.0

---

.ci/scripts/dist_s1/build_dist_s1.sh
.ci/scripts/dist_s1/opera_pge_dist_s1_r2.1_beta_runconfig.yaml
.ci/scripts/dist_s1/test_int_dist_s1.sh
examples/dist_s1_sample_runconfig-v6.0.0-er.2.0.yaml
src/opera/pge/dist_s1/dist_s1_pge.py
src/opera/pge/dist_s1/schema/dist_s1_sas_schema.yaml
src/opera/test/data/test_dist_s1_config.yaml

- This PR integrates DIST-S1 SAS Beta v0.0.8 into the PGE. This SAS version is not a formal delivery, rather an ADT-tagged release image that exposes multiprocessing options deemed important to PCM-PGE integration.
- Closes #660 
- Verified unit tests run successfully
- Verified int test succeeds

DIST-S1 PGE SAS v0.0.9 Integration

---

.ci/docker/Dockerfile_cslc_s1
.ci/docker/Dockerfile_disp_ni
.ci/docker/Dockerfile_disp_s1
.ci/docker/Dockerfile_dist_s1
.ci/docker/Dockerfile_dswx_hls
.ci/docker/Dockerfile_dswx_ni
.ci/docker/Dockerfile_dswx_s1
.ci/docker/Dockerfile_rtc_s1
.ci/docker/Dockerfile_tropo
.ci/jenkins/build-test-deploy/Jenkinsfile

- This PR adds a selectable option to push built PGE Docker images to GHCR in addition to AFN
- Add label to docker images to link GHCR packages to repo
- Closes #653 
- Tested in sandbox

Add optional GHCR push to release pipeline

---

examples/dist_s1_sample_runconfig-v6.0.0-er.3.0.yaml
src/opera/_package.py

Release version 6.0.0-er.3.0 of the DIST-S1 PGE

DIST-S1 PGE release v6.0.0-er.3.0

---

examples/disp_s1_sample_runconfig-v3.0.6.yaml
src/opera/pge/disp_s1/disp_s1_pge.py

Release version 3.0.6 of the DISP-S1 PGE

DISP-S1 PGE Release v3.0.6

---

src/opera/pge/disp_s1/disp_s1_pge.py

- Implement ADT requested renaming of 2 of the DISP-S1-STATIC output bands
- Closes #667 
- Verified unit tests still pass on local & dev

Add band renaming for DISP-S1-STATIC

---

.ci/scripts/disp_ni/build_disp_ni.sh
src/opera/pge/disp_ni/disp_ni_pge.py
src/opera/pge/disp_s1/disp_s1_pge.py
src/opera/test/data/test_disp_ni_config.yaml
src/opera/test/pge/disp_ni/test_disp_ni_pge.py
src/opera/test/pge/disp_s1/test_disp_s1_pge.py
src/opera/util/input_validation.py

- This PR reuses the DISP-S1 input and output validations for the DISP-NI product
- Closes #669 
- Fixed existing unit tests to work with validations enabled
- Added new unit tests for input & output validations

DISP-NI Input/Output validations

---

examples/rtc_s1_sample_runconfig-v2.1.3.yaml
src/opera/pge/rtc_s1/rtc_s1_pge.py

Release version 2.1.3 of the RTC-S1 PGE

RTC-S1 PGE Release v2.1.3

---

examples/dist_s1_sample_runconfig-v6.0.0-rc.1.0.yaml
src/opera/_package.py

Release version 6.0.0-rc.1.0 of the DIST-S1 PGE

DIST-S1 PGE Release v6.0.0-rc.1.0

---

examples/tropo_sample_runconfig-v3.0.0-er.3.1.yaml
src/opera/pge/tropo/tropo_pge.py

Release version 3.0.0-er.3.1 of the TROPO PGE

TROPO PGE Release v3.0.0-er.3.1

---

.secrets.baseline
src/opera/pge/disp_ni/disp_ni_pge.py
src/opera/pge/disp_ni/templates/OPERA_ISO_metadata_L3_DISP_NI_template.xml.jinja2
src/opera/pge/disp_ni/templates/disp_ni_measured_parameters.yaml
src/opera/test/data/test_disp_ni_config.yaml
src/opera/test/data/test_disp_s1_config.yaml
src/opera/test/pge/disp_ni/test_disp_ni_pge.py
src/opera/test/pge/disp_s1/test_disp_s1_pge.py
src/opera/test/util/test_h5_utils.py
src/opera/util/h5_utils.py

- Primary & ancillary file renaming
- Tertiary renaming function created but is currently a no-op pending a confirmed naming convention
- ISO XML generation
- JSON catalog generation
- Closes #696 
- Updated unit tests to check ISO XML creation and validity + catalog metadata creation

DISP-NI PGE Updates

---

examples/disp_ni_sample_runconfig-v6.0.0-er.1.0.yaml
src/opera/pge/disp_ni/disp_ni_pge.py

Release version 6.0.0-er.1.0 of the DISP-NI PGE

DISP-NI PGE Release v6.0.0-er.1.0

---

examples/dswx_s1_sample_runconfig-v3.0.3.yaml
src/opera/pge/dswx_s1/dswx_s1_pge.py

Release version 3.0.3 of the DSWx-S1 PGE

DSWx-S1 PGE Release v3.0.3

---

.ci/scripts/dswx_ni/test_dswx_ni.sh
.ci/scripts/rtc_s1/test_rtc_s1.sh
examples/dist_s1_sample_runconfig-v6.0.0-rc.2.0.yaml
src/opera/_package.py
src/opera/pge/dist_s1/dist_s1_pge.py
src/opera/pge/dist_s1/templates/dist_s1_measured_parameters.yaml
src/opera/test/pge/dist_s1/test_dist_s1_pge.py

Release version 6.0.0-rc.2.0 of the DIST-S1 PGE
Also contains fixes for CI issues discovered while testing this PR

DIST-S1 PGE release v6.0.0-rc.2.0

---

.ci/scripts/dist_s1/build_dist_s1.sh
.ci/scripts/dist_s1/opera_pge_dist_s1_r4_calval_runconfig.yaml
.ci/scripts/util/secrets_scan_compare.sh
examples/dist_s1_sample_runconfig-v6.0.0-rc.2.0.yaml
src/opera/pge/dist_s1/dist_s1_pge.py
src/opera/pge/dist_s1/schema/dist_s1_sas_schema.yaml
src/opera/pge/dist_s1/templates/OPERA_ISO_metadata_L3_DIST_S1_template.xml.jinja2
src/opera/test/data/test_dist_s1_config.yaml
src/opera/util/mock_utils.py

A bug found in the SAS has necessitated a hotfix release of version 2.0.5 of the SAS. We integrate it here. Minor change to the run config so I'm requesting reviews.
- Unit tests are passing
- Integration tests are passing

[RERELEASE] DIST-S1 PGE release v6.0.0-rc.2.0
